apiVersion: ENC[AES256_GCM,data:saE=,iv:1IL5AgPpz85ncPFvjW4nT2Zz1j1pvzCkhvEIJRkzE1I=,tag:ZRjRH5e0yZuHJYrNy8OP6w==,type:str]
kind: ENC[AES256_GCM,data:VtoyqsmJ,iv:9JQEnMW3Ga36A8oeC1szGsUheXjzxTWcaYU6IEGIkxY=,tag:IzZ7KwDPGyoB1NGBE5+lLA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GfMnIjZJCpSnBtk=,iv:Tr7T0vDRoZOsb7BVCMQV5QwPLSKvYXbsAb3mQSnS7A4=,tag:JEBsxe5bBz9qxzG6yka2CQ==,type:str]
    namespace: ENC[AES256_GCM,data:6bCdE7R6NK9H,iv:YorByscFtvXms+DHeL2Zy7bG1JUN2aBCkIlmx6aETeM=,tag:rrt23qdr+jfQ3nCsbXj9Nw==,type:str]
type: ENC[AES256_GCM,data:HmOYVpyN,iv:MpuCgki7VWijlkK/h9IJez9krRKutGScAZdQhEiYr24=,tag:lUuMNFn0TfYtnAJL6/fYrg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:ozLhjq8=,iv:izEHuLatfjU6AfTCTcKnuPLZqWWEiInHW+oWLhWufNc=,tag:cHULlp82L8/+4TfAP0qopQ==,type:str]
    password: ENC[AES256_GCM,data:D6euNR0TplezTWs=,iv:YhgUZ+oUwXbafvlJ9TdZzg3/t/M1L/AOMZUuibBuNa4=,tag:rJrfNl43PeADb43Jz/g91Q==,type:str]
    api_key: ENC[AES256_GCM,data:oSDgQr/QLYra3xqNjgo=,iv:tIXhZhZBxqR70dqNaxIDmqeYzeUT8N2W3kPfEeUgRBM=,tag:pzAm3LjKcERSh7+f1zHW6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zw40j4ax88ljk032zyd7yjr707ejce5ps5nlxmgld6ynwswnc2qcat04y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMS9EcFVkbVkyeDVvTldV
            a3hackJ1eGxHanh2VWlheEhhdURJM3liVlVjCnJabWsrVTU0NjZFUTR5Mmd1bElQ
            bit4YkFXS3dVZWw3YU1iRkYxbE1QcVEKLS0tIG1qWnBTQnJ3eFVPV3E2dS92Mnla
            VzJMSHZiTEtCRjFTaThISUNkTkhBK0EK19liQE0SfWt7ilig+4q1L24+IuE6pqCD
            2XD0VwWA2PUWizJluV/iGL1G6a7sYXmwGtwKg5li6FhDEx3u/DtnBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T06:43:48Z"
    mac: ENC[AES256_GCM,data:jpryPCP/JOOrHNGcfFNMscCay4b0Vjlq1fsK945Ood3WYjCDKgSjtZXpnNxh2gMawmTth58x55lUDMYUGJRpdisZsXPUFEBpNy6KA1tuIimpyRQZQ+OYI05lNT9UVC4o1OZbxOTEwFQLTL/BatTLPEa46ZMzdlZmBWSh0NaLNxc=,iv:jxiyw3dHXEu9RVkRdIyfq+tx/etNEkvte6nHN7tO72E=,tag:rJqPsHmwojBWsZVoMeDptw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
