# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
apiVersion: v2
appVersion: "1.4"
description: intercom service, short ICS, is used to allow inter component API usage
  from the user's webbrowser
keywords:
- ics
- intercom
maintainers:
- name: Univention
  url: https://www.univention.de/
name: intercom-service
type: application
version: 2.23.11
