# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
bases:
  - "../../bases/environments.yaml"
---
repositories:
  # Collabora Online
  # Source: https://github.com/CollaboraOnline/online
  - name: "collabora-online-repo"
    username: {{ .Values.charts.collabora.username | quote }}
    password: {{ .Values.charts.collabora.password | quote }}
    oci: {{ .Values.charts.collabora.oci }}
    url: "{{ .Values.charts.collabora.registry }}/{{ .Values.charts.collabora.repository }}"

releases:
  - name: "collabora-online"
    chart: "collabora-online-repo/{{ .Values.charts.collabora.name }}"
    version: "{{ .Values.charts.collabora.version }}"
    values:
      - "values.yaml"
      - "values.gotmpl"
    installed: {{ .Values.collabora.enabled }}

commonLabels:
  deploy-stage: "component-1"
  component: "collabora"
...
