# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      python-deps:
        patterns:
          - "*"
    commit-message:
      prefix: "build"

  - package-ecosystem: pip
    directory: /scripts/semester-provisioning
    schedule:
      interval: weekly
    groups:
      semester-provisioning-deps:
        patterns:
          - "*"
    commit-message:
      prefix: "build"

  - package-ecosystem: pip
    directory: /scripts/user_import
    schedule:
      interval: weekly
    groups:
      user-import-deps:
        patterns:
          - "*"
    commit-message:
      prefix: "build"

  - package-ecosystem: npm
    directory: /collab-dashboard
    schedule:
      interval: weekly
    groups:
      collab-dashboard-deps:
        patterns:
          - "*"
    commit-message:
      prefix: "build"
