# SPDX-FileCopyrightText: 2026 Zentrum für Digitale Souveränität der Öffentlichen Verwaltung (ZenDiS) GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later
{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencloud.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
data:
  opencloud.yaml: |
    token_manager:
      jwt_secret: "override-via-env"
      machine_auth_api_key: "override-via-env"
      system_user_api_key: "override-via-env"
      transfer_secret: "override-via-env"
      url_signing_secret: "override-via-env"
      system_user_id: {{ .Values.systemUserId | quote }}
    graph:
      application:
        id: {{ .Values.graphApplicationId | quote }}
      events:
        tls_insecure: true
      spaces:
        insecure: true
      identity:
        ldap:
          bind_password: "disabled"
          write_disabled: true
      service_account:
        service_account_id: {{ .Values.serviceAccountId | quote }}
        service_account_secret: "override-via-env"
    collaboration:
      wopi:
        secret: "override-via-env"
      app:
        insecure: true
    proxy:
      oidc:
        insecure: true
      insecure_backends: true
      service_account:
        service_account_id: {{ .Values.serviceAccountId | quote }}
        service_account_secret: "override-via-env"
    frontend:
      app_handler:
        insecure: true
      archiver:
        insecure: true
      service_account:
        service_account_id: {{ .Values.serviceAccountId | quote }}
        service_account_secret: "override-via-env"
    auth_bearer:
      auth_providers:
        oidc:
          insecure: true
    users:
      drivers:
        ldap:
          bind_password: "disabled"
          write_disabled: true
    groups:
      drivers:
        ldap:
          bind_password: "disabled"
          write_disabled: true
    ocdav:
      insecure: true
    ocm:
      service_account:
        service_account_id: {{ .Values.serviceAccountId | quote }}
        service_account_secret: "override-via-env"
    thumbnails:
      thumbnail:
        transfer_secret: "override-via-env"
        webdav_allow_insecure: true
        cs3_allow_insecure: true
    search:
      events:
        tls_insecure: true
      service_account:
        service_account_id: {{ .Values.serviceAccountId | quote }}
        service_account_secret: "override-via-env"
    audit:
      events:
        tls_insecure: true
    settings:
      service_account_ids:
      - {{ .Values.serviceAccountId | quote }}
    sharing:
      events:
        tls_insecure: true
    storage_users:
      events:
        tls_insecure: true
      mount_id: {{ .Values.storageUsersMountId | quote }}
      service_account:
        service_account_id: {{ .Values.serviceAccountId | quote }}
        service_account_secret: "override-via-env"
    notifications:
      notifications:
        events:
          tls_insecure: true
      service_account:
        service_account_id: {{ .Values.serviceAccountId | quote }}
        service_account_secret: "override-via-env"
    nats:
      nats:
        tls_skip_verify_client_cert: true
    gateway:
      storage_registry:
        storage_users_mount_id: {{ .Values.storageUsersMountId | quote }}
    userlog:
      service_account:
        service_account_id: {{ .Values.serviceAccountId | quote }}
        service_account_secret: "override-via-env"
    auth_service:
      service_account:
        service_account_id: {{ .Values.serviceAccountId | quote }}
        service_account_secret: "override-via-env"
    clientlog:
      service_account:
        service_account_id: {{ .Values.serviceAccountId | quote }}
        service_account_secret: "override-via-env"
    activitylog:
      service_account:
        service_account_id: {{ .Values.serviceAccountId | quote }}
        service_account_secret: "override-via-env"
{{- end }}
