# SPDX-FileCopyrightText: 2026 Zentrum für Digitale Souveränität der Öffentlichen Verwaltung (ZenDiS) GmbH
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencloud.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
type: Opaque
stringData:
  oc-jwt-secret: {{ .Values.jwtSecret | default (randAlphaNum 32) | quote }}
  oc-transfer-secret: {{ .Values.transferSecret | default (randAlphaNum 32) | quote }}
  oc-machine-auth-api-key: {{ .Values.machineAuthApiKey | default (randAlphaNum 32) | quote }}
  oc-system-user-api-key: {{ .Values.systemUserApiKey | default (randAlphaNum 32) | quote }}
  oc-url-signing-secret: {{ .Values.urlSigningSecret | default (randAlphaNum 32) | quote }}
  oc-oidc-client-secret: {{ .Values.oidc.clientSecret | default (randAlphaNum 32) | quote }}
