# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
extends:
  - '@commitlint/config-conventional'
rules:
  type-enum:
    - 2
    - always
    - - feat
      - fix
      - docs
      - style
      - refactor
      - perf
      - test
      - build
      - ci
      - chore
      - revert
  scope-enum:
    - 0
    - always
  header-max-length:
    - 2
    - always
    - 100
