apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: drawio
    meta.helm.sh/release-namespace: opendesk
  labels:
    app.kubernetes.io/instance: drawio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: drawio
    helm.sh/chart: drawio-29.6.3
  name: drawio-drawio-ingress
namespace: opendesk
spec:
  ingressClassName: haproxy
  rules:
  - host: draw.opendesk.hrz.uni-marburg.de
    http:
      paths:
      - backend:
          service:
            name: drawio-drawio
            port:
              number: 80
        path: /
        pathType: Prefix
