# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
bases:
  - "../../bases/environments.yaml"
---
repositories:
  # VMWare Bitnami
  # Source: https://github.com/bitnami/charts/
  - name: "keycloak-repo"
    oci: true
    keyring: "../../files/gpg-pubkeys/souvap-univention-de.gpg"
    verify: {{ .Values.charts.keycloak.verify }}
    username: "{{ .Values.charts.keycloak.username }}"
    password: {{ .Values.charts.keycloak.password | quote }}
    url: "{{ .Values.charts.keycloak.registry }}/{{ .Values.charts.keycloak.repository }}"

  # openDesk Keycloak Theme
  # Source: https://gitlab.opencode.de/bmi/opendesk/components/charts/opendesk-keycloak-theme
  - name: "keycloak-theme-repo"
    oci: true
    keyring: "../../files/gpg-pubkeys/souvap-univention-de.gpg"
    verify: {{ .Values.charts.keycloakTheme.verify }}
    username: "{{ .Values.charts.keycloakTheme.username }}"
    password: {{ .Values.charts.keycloakTheme.password | quote }}
    url: "{{ .Values.charts.keycloakTheme.registry }}/{{ .Values.charts.keycloakTheme.repository }}"

  # openDesk Keycloak Extensions
  - name: "keycloak-extensions-repo"
    username: "{{ .Values.charts.keycloakExtensions.username }}"
    password: {{ .Values.charts.keycloakExtensions.password | quote }}
    url: "{{ .Values.charts.keycloakExtensions.registry }}/{{ .Values.charts.keycloakExtensions.repository }}"

releases:
  - name: "keycloak-theme"
    chart: "keycloak-theme-repo/{{ .Values.charts.keycloakTheme.name }}"
    version: "{{ .Values.charts.keycloakTheme.version }}"
    values:
      - "values-theme.gotmpl"
    installed: {{ .Values.keycloak.enabled }}

  - name: "keycloak"
    chart: "keycloak-repo/{{ .Values.charts.keycloak.name }}"
    version: "{{ .Values.charts.keycloak.version }}"
    values:
      - "values-keycloak.gotmpl"
      - "values-keycloak.yaml"
      - "values-keycloak-idp.yaml"
    wait: true
    installed: {{ .Values.keycloak.enabled }}

  - name: "keycloak-extensions"
    chart: "keycloak-extensions-repo/{{ .Values.charts.keycloakExtensions.name }}"
    version: "{{ .Values.charts.keycloakExtensions.version }}"
    needs:
      - "keycloak"
    values:
      - "values-extensions.yaml"
      - "values-extensions.gotmpl"
    installed: {{ .Values.keycloak.enabled }}

commonLabels:
  deploy-stage: "component-1"
  component: "keycloak"
...
