{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opencloud-sidecar.fullname" . }}-data
  labels:
    {{- include "opencloud-sidecar.labels" . | nindent 4 }}
    backup-tier: "b"
    k8up/backup: "true"
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
