apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db
    namespace: opendesk
    labels:
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/part-of: opendesk
type: Opaque
stringData:
    db-password: ENC[AES256_GCM,data:H8sjS0HrTK7tUxEfcVlIr4eVubrS8io4rzhk4XN+Aw==,iv:q3KNdK0DYxnt+0qOrB4OODUyUqjfcG1TojkQtlzBtwc=,tag:sFuGURb3gDLOx+5NbWookQ==,type:str]
    admin-password: ENC[AES256_GCM,data:g6L9BVam/nlhHTyvZliGGXL4DisStctWGqz3OsqYx9s=,iv:pJbsS0uWw25SuLgig4ftxIGWHkKRw2Lrogsr3rWK65Y=,tag:PKkJ/buf78eib5DSK6WHXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15437xk7432fpwtrd2gpwcmh7xyzacvp2sy6qr5sq2n3zqah5u9tqw5s539
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdU9vdGlDR1lVRzJONTV3
            OVllcWdPRXpZcHJzdGNjcGdJZVhDM2FBUkEwClQ2Q3UwMWJJckppcW1tR1VtRWhm
            ZEtRTkNNS2NydDZZdkVkaGxXc1J1cUEKLS0tIDIvVGNjZmxjVlAzZUlCVU5GUXZ1
            ZWNKQWlEaXduRXlaU3JQN1U1WWNBZUkKIVdDdViOqLsI0CIhg5tKLs8LQXtvN9I6
            bS80gsme+XnPkFN37dL7QsbRZk/bXtATxHzb6eiFhxCIDwghlsdekQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T07:33:48Z"
    mac: ENC[AES256_GCM,data:PoYSSvOEbmrhYb1IQPOck/USLntdegU7p1r0izhYwADRAmY5cYwOzh7UNprU90Pv8aNoy38Wb4V4clqxt3xv9B4qOQgVR5IY1fYFqakyOlUnfSvKCrx148x80cGvd87s8Viwvv7pFPDvgMBbMa1QjnTt668ZUIbUgqTqyj/cQOI=,iv:IOC58JsypmlCAGHHihkQf4JYD53NCVKI4vyitdq7VPQ=,tag:wRGbuVfa5GzAie8vBthqHg==,type:str]
    pgp: []
    encrypted_regex: ^(db-password|admin-password|password|secret|apiKey|token|privateKey|root-password|mariadb-root-password|mysql-root-password|keycloak|opencloud|sogo|sogo6|synapse)$
    version: 3.9.4
