#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
"""
YAML Spec → Playwright Test Generator

Reads declarative YAML test specs from tests/specs/*.yaml and generates
Playwright .spec.js files that can be executed via npx playwright test.

This ensures the YAML specs remain the single source of truth for ICS
integration testing, with both CLI and browser-level execution paths.

Usage:
    python tests/generate-playwright-specs.py                         # Generate all
    python tests/generate-playwright-specs.py tests/specs/ics-routing.yaml  # One spec
    python tests/generate-playwright-specs.py --watch                 # Regen on change
"""

import os
import sys
import glob
import json
import hashlib
import argparse
import yaml
from datetime import datetime


HEADER = """/**
 * Auto-generated ICS Integration Test Spec
 * Generated by tests/generate-playwright-specs.py
 * Source: {source}
 * Generated: {timestamp}
 *
 * Do not edit directly — edit the YAML spec file and regenerate.
 *
 * Run: npx playwright test {output}
 */

const {{ test, expect }} = require('@playwright/test');

const CFG = {{
  ics: process.env.ICS_BASE_URL || '{ics_base}',
  portal: process.env.PORTAL_URL || 'https://portal.opendesk.hrz.uni-marburg.de',
  creds: {{
    username: process.env.PORTAL_USERNAME || '',
    password: process.env.PORTAL_PASSWORD || '',
  }},
  timeouts: {{
    nav: 30000,
    redirect: 20000,
    auth: 45000,
  }},
}};

function skipWithoutCreds() {{
  if (!CFG.creds.username || !CFG.creds.password) {{
    console.warn('⚠ Skipping — set PORTAL_USERNAME/PASSWORD');
    return true;
  }}
  return false;
}}

async function loginThroughIcs(page, route) {{
  await page.goto(`${{CFG.ics}}${{route}}`, {{
    waitUntil: 'networkidle',
    timeout: CFG.timeouts.nav,
  }});
  for (let attempt = 0; attempt < 3; attempt++) {{
    const url = page.url();
    if (!url.startsWith(CFG.ics) && !url.includes('/realms/') && !url.includes('/idp/') && !url.includes('login')) break;
    const usernameInput = page.locator('input[name="username"], input[id="username"], input[name="j_username"]').first();
    if (await usernameInput.isVisible({{ timeout: 5000 }}).catch(() => false)) {{
      await usernameInput.fill(CFG.creds.username);
      const pwInput = page.locator('input[name="password"], input[id="password"], input[name="j_password"], input[name="pass"]').first();
      if (await pwInput.isVisible({{ timeout: 3000 }}).catch(() => false)) {{
        await pwInput.fill(CFG.creds.password);
      }}
      await page.click('input[type="submit"], button[type="submit"]');
      await page.waitForLoadState('networkidle', {{ timeout: CFG.timeouts.auth }});
    }}
    if (url.startsWith(CFG.portal)) {{
      const loginBtn = page.locator('button:has-text("Login"), a:has-text("Login")').first();
      if (await loginBtn.isVisible().catch(() => false)) {{
        await loginBtn.click();
        await page.waitForLoadState('networkidle', {{ timeout: CFG.timeouts.auth }});
      }}
    }}
  }}
}}
"""


FOOTER = ""  # We close in generate_service_tests


def slugify(name):
    return name.lower().replace(' ', '_').replace('/', '_').replace('-', '_')[:60]


def sanitize_test_name(name):
    return name.replace('"', "'")


def generate_service_tests(spec_data, source_path):
    spec_name = spec_data.get("name", "ICS Spec")
    base_url = spec_data.get("base_url", "https://ics.opendesk.hrz.uni-marburg.de")
    output_path = source_path.replace(".yaml", ".spec.js").replace("specs/", "playwright/")
    header = HEADER.format(
        source=os.path.basename(source_path),
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        output=os.path.basename(output_path),
        ics_base=base_url,
    )
    lines = [header]
    lines.append(f'\ntest.describe("{spec_name}", () => {{')

    for svc_key, svc in spec_data.get("services", {}).items():
        route = svc.get("route", "/")
        svc_auth = svc.get("auth", "none")
        svc_label = svc_key.capitalize()
        lines.append(f'\n  test.describe("{svc_label} (route {route})", () => {{')

        for test_def in svc.get("tests", []):
            scenario = test_def.get("scenario", "Unnamed")
            auth_type = test_def.get("auth", "none")
            test_slug = slugify(scenario)

            lines.append(f'\n    test("{sanitize_test_name(scenario)}", async ({{ page, context }}) => {{')

            if auth_type in ("session", "oidc"):
                lines.append(f'      if (skipWithoutCreds()) {{ test.skip(); return; }}')

                has_header_check = any(
                    "headers" in step.get("expect", {})
                    for step in test_def.get("steps", [])
                )
                if has_header_check:
                    lines.append(f'      let headers = {{}};')
                    lines.append(f'      page.on("response", (resp) => {{')
                    lines.append(f'        const xfu = resp.headers()["x-forwarded-user"];')
                    lines.append(f'        const xfh = resp.headers()["x-forwarded-host"];')
                    lines.append(f'        if (xfu) headers["x-forwarded-user"] = xfu;')
                    lines.append(f'        if (xfh) headers["x-forwarded-host"] = xfh;')
                    lines.append(f'      }});')

                lines.append(f'      await loginThroughIcs(page, "{route}");')

            for step_idx, step in enumerate(test_def.get("steps", [])):
                expect = step.get("expect", {})
                request = step.get("request", {})
                path = request.get("path", route)

                # Generate navigation for non-auth scenarios
                if auth_type in (None, "none") or step_idx > 0:
                    lines.append(f'      await page.goto(`${{CFG.ics}}{path}`, {{')
                    lines.append(f'        waitUntil: "domcontentloaded",')
                    lines.append(f'        timeout: CFG.timeouts.nav,')
                    lines.append(f'      }});')
                    lines.append(f'      await page.waitForTimeout(2000);')

                # Generate assertions
                status = expect.get("status", [200])
                if isinstance(status, int):
                    status = [status]

                redirect = expect.get("redirect_contains", "")
                headers_expect = expect.get("headers", {})

                assertions = []

                if redirect:
                    assertions.append(
                        f'      expect(page.url()).toContain("{redirect}");'
                    )
                elif status:
                    if 302 in status or 307 in status:
                        assertions.append(
                            f'      const redirected = !page.url().startsWith(CFG.ics);'
                        )
                        assertions.append(
                            f'      expect(redirected).toBeTruthy();'
                        )
                    else:
                        assertions.append(
                            f'      const pageLoaded = await page.locator("body").isVisible().catch(() => false);'
                        )
                        assertions.append(
                            f'      expect(pageLoaded).toBeTruthy();'
                        )

                for hdr, hdr_val in headers_expect.items():
                    hdr_name = hdr.lower()
                    soft_fail = False
                    expected_value = hdr_val

                    if isinstance(hdr_val, dict):
                        expected_value = hdr_val.get("value", "present")
                        soft_fail = hdr_val.get("soft_fail", False)

                    hdr_key = hdr_name.replace("-", "_")
                    if expected_value == "present":
                        if soft_fail:
                            assertions.append(
                                f'      if (headers["{hdr_name}"]) console.log("{hdr_name} captured");'
                                f' else console.log("{hdr_name} not captured (auth chain may not have completed)");'
                            )
                        else:
                            assertions.append(
                                f'      expect(headers["{hdr_name}"]).toBeTruthy();'
                            )
                    else:
                        if soft_fail:
                            assertions.append(
                                f'      if (headers["{hdr_name}"]) expect(headers["{hdr_name}"]).toBe("{expected_value}");'
                                f' else console.log("{hdr_name} not captured (auth chain may not have completed)");'
                            )
                        else:
                            assertions.append(
                                f'      expect(headers["{hdr_name}"]).toBe("{expected_value}");'
                            )

                if assertions:
                    lines.append(f'      // Step {step_idx + 1}: verify expectations')
                    lines.extend(assertions)

                # Add evidence screenshot
                if step_idx == len(test_def.get("steps", [])) - 1:
                    lines.append(f'      await page.screenshot({{')
                    lines.append(f'        path: `.sisyphus/evidence/gen-{test_slug}.png`,')
                    lines.append(f'        fullPage: true,')
                    lines.append(f'      }});')

            lines.append(f'    }});')

        lines.append(f'  }});')

    lines.append(f'\n  test.describe("Backchannel logout (generated)", () => {{')
    for svc_key, svc in spec_data.get("services", {}).items():
        route = svc.get("route", "/")
        svc_label = svc_key.capitalize()
        test_slug = slugify(f"{svc_key}_logout")
        lines.append(f'''
    test("{svc_label}: session terminated after portal logout", async ({{ page }}) => {{
      if (skipWithoutCreds()) {{ test.skip(); return; }}
      await loginThroughIcs(page, "{route}");
      await page.goto(CFG.portal, {{ waitUntil: "networkidle", timeout: CFG.timeouts.nav }});
      const logoutBtn = page.locator('button:has-text("Logout"), a:has-text("Logout")').first();
      if (await logoutBtn.isVisible().catch(() => false)) {{
        await logoutBtn.click();
        await page.waitForLoadState("networkidle", {{ timeout: CFG.timeouts.auth }});
      }}
      await page.waitForTimeout(5000);
      await page.goto(`${{CFG.ics}}{route}`, {{ waitUntil: "domcontentloaded", timeout: CFG.timeouts.nav }});
      await page.waitForTimeout(3000);
      const afterLogout = page.url();
      const needsReauth = afterLogout.includes("/realms/") && !afterLogout.includes("code=");
      console.log(`{svc_label} post-logout: ${{afterLogout.substring(0, 100)}} → reauth: ${{needsReauth}}`);
      expect(needsReauth || !afterLogout.includes("{route}")).toBeTruthy();
      await page.screenshot({{ path: `.sisyphus/evidence/gen-{test_slug}.png`, fullPage: true }});
    }});
''')
    lines.append(f'  }});')

    lines.append(f'}});')
    return "\n".join(lines), output_path


def generate_all(spec_dir, output_base):
    spec_files = sorted(glob.glob(os.path.join(spec_dir, "*.yaml")))
    generated = []
    for spec_path in spec_files:
        with open(spec_path) as f:
            spec_data = yaml.safe_load(f)
        content, output_path = generate_service_tests(spec_data, spec_path)
        output_path = os.path.join(output_base, os.path.basename(output_path))
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w") as f:
            f.write(content)
        generated.append((spec_path, output_path))
    return generated


def main():
    parser = argparse.ArgumentParser(
        description="Generate Playwright tests from YAML spec files"
    )
    parser.add_argument("specs", nargs="*", default=[],
                        help="Spec files to process (default: tests/specs/*.yaml)")
    parser.add_argument("--spec-dir", default=None,
                        help="Spec directory (default: tests/specs/)")
    parser.add_argument("--output-dir", default=None,
                        help="Output directory (default: tests/playwright/)")
    parser.add_argument("--watch", action="store_true",
                        help="Watch for changes (requires watchfiles)")
    args = parser.parse_args()

    script_dir = os.path.dirname(__file__)
    spec_dir = args.spec_dir or os.path.join(script_dir, "specs")
    output_dir = args.output_dir or os.path.join(script_dir, "playwright")

    generated = generate_all(spec_dir, output_dir)

    print(f"Generated {len(generated)} Playwright spec file(s):")
    for src, dst in generated:
        rel_src = os.path.relpath(src)
        rel_dst = os.path.relpath(dst)
        src_size = os.path.getsize(src)
        dst_size = os.path.getsize(dst)
        print(f"  {rel_src} ({src_size}B) → {rel_dst} ({dst_size}B)")

    if args.watch:
        try:
            from watchfiles import watch
            print("\nWatching for changes...")
            for changes in watch(spec_dir):
                for change_type, change_path in changes:
                    if change_path.endswith(".yaml"):
                        print(f"\nChange detected: {change_path}")
                        spec_path = change_path
                        with open(spec_path) as f:
                            spec_data = yaml.safe_load(f)
                        content, output_path = generate_service_tests(
                            spec_data, spec_path
                        )
                        output_path = os.path.join(
                            output_dir, os.path.basename(output_path)
                        )
                        with open(output_path, "w") as f:
                            f.write(content)
                        print(f"  Regenerated: {output_path}")
        except ImportError:
            print("watchfiles not installed. Install with: pip install watchfiles")
            sys.exit(1)


if __name__ == "__main__":
    main()
