# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
appVersion: "11.4.4"
description: A Helm chart for the openDesk ILIAS MariaDB database
home: https://github.com/opendesk-edu/opendesk-edu
name: mariadb
type: application
version: 0.1.0
