{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hessenbox-sidecar.fullname" . }}-credentials
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    {{- include "hessenbox-sidecar.labels" . | nindent 4 }}
    app: {{ include "hessenbox-sidecar.name" . }}
type: Opaque
data:
  username: {{ .Values.hessenbox.username | b64enc | quote }}
  password: {{ .Values.hessenbox.password | b64enc | quote }}
{{- end -}}
