# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: "kyverno.io/v1"
kind: "ClusterPolicy"
metadata:
  name: "require-imagepullsecrets"
spec:
  background: true
  rules:
    - match:
        resources:
          kinds:
            - "Pod"
      name: "require-imagepullsecrets"
      validate:
        message: "ImagePullSecrets are required."
        pattern:
          spec:
            imagePullSecrets:
              - name: "*"
  validationFailureAction: "audit"
...
