# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: GPL-3.0-or-later
{{- $secretName := include "paperless-ngx.oidcSecret" . }}
{{- $redisSecretName := include "paperless-ngx.redisSecret" . }}
{{- $databaseSecretName := include "paperless-ngx.databaseSecret" . }}
{{- $emailSecretName := include "paperless-ngx.emailSecret" . }}

{{- if not .Values.paperless.oidc.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-secret: {{ .Values.paperless.oidc.clientSecret | default (randAlphaNum 64) | quote }}
  secret-key: {{ .Values.paperless.secretKey | default (randAlphaNum 64) | quote }}
---
{{- end }}

{{- if not .Values.paperless.redis.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $redisSecretName }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ .Values.paperless.redis.password | default (randAlphaNum 32) | quote }}
---
{{- end }}

{{- if not .Values.paperless.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $databaseSecretName }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgresql-password: {{ .Values.paperless.database.password | default (randAlphaNum 32) | quote }}
---
{{- end }}

{{- if not .Values.paperless.email.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $emailSecretName }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.paperless.email.imap.username | default "" | quote }}
  password: {{ .Values.paperless.email.imap.password | default "" | quote }}
{{- end -}}
