{{- if .Values.serviceAccount.create }}
# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: GPL-3.0-or-later
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "paperless-ngx.serviceAccountName" . }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end -}}
