# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seaweedfs.s3Fullname" . }}
  labels:
    {{- include "seaweedfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: s3
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8333
      targetPort: http
      protocol: TCP
  selector:
    {{- include "seaweedfs.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: s3
