# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seaweedfs.fullname" . }}
  labels:
    {{- include "seaweedfs.labels" . | nindent 4 }}
type: Opaque
stringData:
  accessKey: {{ .Values.auth.accessKey | default "" | quote }}
  secretKey: {{ .Values.auth.secretKey | default "" | quote }}
  adminPassword: {{ .Values.auth.adminPassword | default "" | quote }}
