# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
appVersion: "0.1.0"
description: EUDI Verifiable Credential Issuer Service for openDesk Edu
home: https://github.com/opendesk-edu/opendesk-edu
name: eudi-issuer
type: application
version: 0.1.0
