apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "smoke-tests.fullname" . }}
  labels:
    {{- include "smoke-tests.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
      ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
      template:
        metadata:
          labels:
            {{- include "smoke-tests.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          containers:
            - name: smoke-test
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - /bin/sh
                - /scripts/e2e-test.sh
              volumeMounts:
                - name: script
                  mountPath: /scripts
                  readOnly: true
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          volumes:
            - name: script
              configMap:
                name: {{ include "smoke-tests.fullname" . }}-script
                defaultMode: 0555
