# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
bases:
  - "../../bases/environments.yaml"
---
repositories:
  # openDesk Univention Corporate Server (as eval Container)
  - name: "univention-corporate-container-repo"
    oci: true
    keyring: "../../files/gpg-pubkeys/souvap-univention-de.gpg"
    verify: {{ .Values.charts.univentionCorporateServer.verify }}
    username: "{{ .Values.charts.univentionCorporateServer.username }}"
    password: {{ .Values.charts.univentionCorporateServer.password | quote }}
    url: "{{ .Values.charts.univentionCorporateServer.registry }}/\
      {{ .Values.charts.univentionCorporateServer.repository }}"

releases:
  - name: "univention-corporate-container"
    chart: "univention-corporate-container-repo/{{ .Values.charts.univentionCorporateServer.name }}"
    version: "{{ .Values.charts.univentionCorporateServer.version }}"
    values:
      - "values.yaml"
      - "values.gotmpl"
    installed: {{ .Values.univentionCorporateServer.enabled }}

commonLabels:
  deploy-stage: "component-1"
  component: "univention-corporate-container"
...
