# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-typo3-config
  labels:
{{ include "typo3.labels" . | nindent 4 }}
data:
  AdditionalConfiguration.php: |-
    <?php
    return [
        'BE' => [
            'installToolPassword' => '{{ .Values.typo3.installToolPassword }}',
        ],
        'DB' => [
            'Connections' => [
                'Default' => [
                    'charset' => 'utf8mb4',
                    'dbname' => '{{ include "typo3.dbName" . }}',
                    'driver' => 'mysqli',
                    'host' => '{{ include "typo3.dbHost" . }}',
                    'password' => '{{ include "typo3.dbPassword" . }}',
                    'port' => {{ include "typo3.dbPort" . }},
                    'user' => '{{ include "typo3.dbUser" . }}',
                ],
            ],
        ],
        'SYS' => [
            'trustedHostsPattern' => '{{ (index .Values.ingress.hosts 0).host }}',
            'sitename' => 'TYPO3 CMS',
        ],
        'TYPO3_CONTEXT' => 'Production',
    ];
