# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-typo3-fileadmin
  labels:
{{ include "typo3.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.typo3.volumes.fileadmin.accessMode }}
  resources:
    requests:
      storage: {{ .Values.typo3.volumes.fileadmin.size }}
  {{- if .Values.typo3.volumes.fileadmin.storageClass }}
  storageClassName: {{ .Values.typo3.volumes.fileadmin.storageClass }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-typo3-var
  labels:
{{ include "typo3.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.typo3.volumes.var.accessMode }}
  resources:
    requests:
      storage: {{ .Values.typo3.volumes.var.size }}
  {{- if .Values.typo3.volumes.var.storageClass }}
  storageClassName: {{ .Values.typo3.volumes.var.storageClass }}
  {{- end }}
