# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-typo3-secret
  labels:
{{ include "typo3.labels" . | nindent 4 }}
type: Opaque
data:
  typo3-db-password: {{ include "typo3.dbPassword" . | b64enc }}
  typo3-install-tool-password: {{ .Values.typo3.installToolPassword | b64enc }}
