# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: Apache-2.0
{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-database-credentials" (include "mariadb.fullname" .) }}
  labels:
{{ include "mariadb.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ randAlphaNum 32 | b64enc | quote }}
  root-password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
