# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
bases:
  - "../../bases/environments.yaml"
---
repositories:
  # CryptPad
  # Source: https://github.com/cryptpad/helm
  - name: "cryptpad-repo"
    username: "{{ .Values.charts.cryptpad.username }}"
    password: {{ .Values.charts.cryptpad.password | quote }}
    url: "{{ .Values.charts.cryptpad.registry }}/{{ .Values.charts.cryptpad.repository }}"

releases:
  - name: "cryptpad"
    chart: "cryptpad-repo/{{ .Values.charts.cryptpad.name }}"
    version: "{{ .Values.charts.cryptpad.version }}"
    values:
      - "values.yaml"
      - "values.gotmpl"
    installed: {{ .Values.cryptpad.enabled }}

commonLabels:
  deploy-stage: "component-1"
  component: "cryptpad"
...
