# SPDX-FileCopyrightText: 2026 Zentrum für Digitale Souveränität der Öffentlichen Verwaltung (ZenDiS) GmbH
# SPDX-License-Identifier: Apache-2.0

replicaCount: 2

image:
  registry: docker.io
  repository: <your-org>/opencloud
  tag: v1.0.0
  pullPolicy: IfNotPresent

podAnnotations: {}

securityContext:
  fsGroup: 1000

containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault

service:
  type: ClusterIP
  port: 8080
  annotations: {}

ingress:
  enabled: true
  className: haproxy
  annotations:
    haproxy-ingress.github.io/ssl-redirect: "true"
    haproxy-ingress.github.io/proxy-body-size: "100M"
    haproxy-ingress.github.io/timeout-server: "600s"
    haproxy-ingress.github.io/timeout-client: "600s"
  hosts:
    - host: opencloud.opendesk.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: opendesk-certificates-tls
      hosts:
        - opencloud.opendesk.example.com

persistence:
  enabled: true
  size: 100Gi
  accessMode: ReadWriteMany
  storageClass: "ceph-cephfs-hdd-ec"
  annotations: {}

oidc:
  issuer: https://id.opendesk.example.com/realms/opendesk
  internalIssuer: ""
  clientId: opendesk-opencloud
  clientSecret: ""
  autoProvisionAccounts: "true"
  roleAssignmentDriver: "oidc"
  rewriteWellknown: "true"
  userOidcClaim: "sub"
  userCs3Claim: "sub"
  autoProvisionClaimUsername: "preferred_username"
  adminUserId: ""
  defaultAssignments: "false"
  assignDefaultUserRole: "false"
  usernameMatch: "none"
  excludeRunServices: "idp,idm,auth-basic"
  accountEditLink: https://id.opendesk.example.com/realms/opendesk/account

logLevel: info

jwtSecret: ""

transferSecret: ""

machineAuthApiKey: ""

systemUserApiKey: ""

systemUserId: ""

urlSigningSecret: ""

serviceAccountId: "dc3eee3e-7831-45e4-b986-8e470f37ac23"

storageUsersMountId: "ca65db73-407e-43ca-b393-9b141f43aa8f"

graphApplicationId: "fdfc30d2-5cc5-40a4-8beb-ce6801bbca41"

config:
  enabled: true

serviceAccount:
  create: true
  annotations: {}

nodeSelector: {}

tolerations: []

affinity: {}

resources:
  requests:
    cpu: 256m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
