# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mariadb
  labels:
{{ include "bookstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector:
{{ include "bookstack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
{{- end }}
