apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-moodle-data
  namespace: {{ .Release.Namespace }}
  labels:
    backup-tier: "b"
    k8up/backup: "true"
spec:
  accessModes:
    - {{ .Values.moodle.volumes.data.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.moodle.volumes.data.size | quote }}
  {{- if .Values.moodle.volumes.data.storageClass }}
  storageClassName: {{ .Values.moodle.volumes.data.storageClass | quote }}
  {{- end }}
