{{/*
Create a secret for Moodle credentials
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-moodle-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "moodle.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.moodle.moodlePassword }}
  moodle-password: {{ .Values.moodle.moodlePassword | b64enc | quote }}
  {{- else }}
  moodle-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  moodle-username: {{ .Values.moodle.moodleUsername | b64enc | quote }}
  moodle-email: {{ .Values.moodle.moodleEmail | b64enc | quote }}
