apiVersion: v1
kind: ConfigMap
metadata:
  name: ums-portal-frontend-nginx
  namespace: opendesk-edu
data:
  nginx.conf: |
    worker_processes  auto;
    error_log  /dev/stderr notice;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        server_tokens off;
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log  /dev/stdout  main;
        sendfile        on;
        keepalive_timeout  65;
        sub_filter_once off;
        sub_filter_types text/html;

        server {
            listen 80 default_server;
            listen [::]:80 default_server;
            root /var/www/html;
            index index.html index.htm;
            server_name _;
            absolute_redirect off;

            location /js/domain-aware.js {
                alias /var/www/html/js/domain-aware.js;
                types {
                    text/javascript js;
                }
            }

            location /univention/portal/js/domain-aware.js {
                alias /var/www/html/js/domain-aware.js;
                types {
                    text/javascript js;
                }
            }

            location = / {
                return 301 /univention/portal/;
            }
            location = /univention {
                return 301 /univention/portal/;
            }
            location = /univention/ {
                return 301 /univention/portal/;
            }

            location = /univention/portal {
                return 301 /univention/portal/;
            }
            location = /univention/selfservice {
                return 301 /univention/selfservice/;
            }

            location /univention/portal/icons/ {
                alias /var/www/portal-assets/icons/;
                try_files $uri =404;
            }

            location /univention/portal/ {
                sub_filter '<script defer="defer" src="js/chunk-vendors.js"></script>' '<script defer="defer" src="js/chunk-vendors.js"></script><script src="/univention/portal/js/domain-aware.js"></script>';
                try_files $uri $uri/ /univention/portal/index.html;
            }

            location /univention/selfservice/ {
                sub_filter '<script defer="defer" src="js/chunk-vendors.js"></script>' '<script defer="defer" src="js/chunk-vendors.js"></script><script src="/univention/selfservice/js/domain-aware.js"></script>';
                try_files $uri $uri/ /univention/selfservice/index.html;
            }

            location = /favicon.ico {
                alias /var/www/html/favicon/favicon.ico;
            }
            location /favicon/ {
                try_files $uri =404;
            }

            location / {
                try_files $uri $uri/ =404;
            }
        }
    }