{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "slidev.fullname" . }}-slides
  labels:
    {{- include "slidev.labels" . | nindent 4 }}
    backup-tier: "c"
    k8up/backup: "true"
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
