apiVersion: v1
kind: Service
metadata:
  name: {{ include "slidev.fullname" . }}
  labels:
    {{- include "slidev.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ if .Values.oauth2.enabled }}oauth2{{ else }}http{{ end }}
      protocol: TCP
      name: http
  selector:
    {{- include "slidev.selectorLabels" . | nindent 4 }}
