# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.bigbluebutton.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-greenlight-hpa
  labels:
    app: {{ .Release.Name }}-greenlight
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-greenlight
  minReplicas: {{ .Values.bigbluebutton.hpa.minReplicas | default 1 }}
  maxReplicas: {{ .Values.bigbluebutton.hpa.maxReplicas | default 5 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.bigbluebutton.hpa.targetCPUUtilizationPercentage | default 70 }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.bigbluebutton.hpa.targetMemoryUtilizationPercentage | default 80 }}
{{- end }}
