# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: Apache-2.0
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-greenlight-pdb
  labels:
    app: {{ .Release.Name }}-greenlight
spec:
  minAvailable: {{ if .Values.pdb }}{{ .Values.pdb.minAvailable | default 1 }}{{ else }}1{{ end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-greenlight
