apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-bbb-recordings
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.bigbluebutton.volumes.recordings.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.bigbluebutton.volumes.recordings.size | quote }}
  {{- if .Values.bigbluebutton.volumes.recordings.storageClass }}
  storageClassName: {{ .Values.bigbluebutton.volumes.recordings.storageClass | quote }}
  {{- end }}
