apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-greenlight-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-greenlight
type: Opaque
stringData:
  secret-key-base: {{ .Values.bigbluebutton.greenlight.secretKeyBase | default (randAlphaNum 64) | quote }}
  {{- if .Values.bigbluebutton.greenlight.bigbluebuttonSecret }}
  bbb-secret: {{ .Values.bigbluebutton.greenlight.bigbluebuttonSecret | quote }}
  {{- end }}
