apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.bigbluebutton.service.annotations }}
    {{- range $key, $value := .Values.bigbluebutton.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.bigbluebutton.service.externalPort }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-greenlight
