# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
bases:
  - "../../bases/environments.yaml"
---
repositories:
  # Univention Management Stack
  - name: "ums-guardian-management-api-repo"
    keyring: "../../files/gpg-pubkeys/univention-de.gpg"
    verify: {{ .Values.charts.umsGuardianManagementApi.verify }}
    username: {{ env "OD_PRIVATE_REGISTRY_USERNAME" | quote }}
    password: {{ env "OD_PRIVATE_REGISTRY_PASSWORD" | quote }}
    oci: true
    url: "{{ .Values.global.helmRegistry | default .Values.charts.umsGuardianManagementApi.registry }}/\
      {{ .Values.charts.umsGuardianManagementApi.repository }}"
  - name: "ums-guardian-management-ui-repo"
    keyring: "../../files/gpg-pubkeys/univention-de.gpg"
    verify: {{ .Values.charts.umsGuardianManagementUi.verify }}
    username: {{ env "OD_PRIVATE_REGISTRY_USERNAME" | quote }}
    password: {{ env "OD_PRIVATE_REGISTRY_PASSWORD" | quote }}
    oci: true
    url: "{{ .Values.global.helmRegistry | default .Values.charts.umsGuardianManagementUi.registry }}/\
      {{ .Values.charts.umsGuardianManagementUi.repository }}"
  - name: "ums-guardian-authorization-api-repo"
    keyring: "../../files/gpg-pubkeys/univention-de.gpg"
    verify: {{ .Values.charts.umsGuardianAuthorizationApi.verify }}
    username: {{ env "OD_PRIVATE_REGISTRY_USERNAME" | quote }}
    password: {{ env "OD_PRIVATE_REGISTRY_PASSWORD" | quote }}
    oci: true
    url: "{{ .Values.global.helmRegistry | default .Values.charts.umsGuardianAuthorizationApi.registry }}/\
      {{ .Values.charts.umsGuardianAuthorizationApi.repository }}"
  - name: "ums-open-policy-agent-repo"
    keyring: "../../files/gpg-pubkeys/univention-de.gpg"
    verify: {{ .Values.charts.umsOpenPolicyAgent.verify }}
    username: {{ env "OD_PRIVATE_REGISTRY_USERNAME" | quote }}
    password: {{ env "OD_PRIVATE_REGISTRY_PASSWORD" | quote }}
    oci: true
    url: "{{ .Values.global.helmRegistry | default .Values.charts.umsOpenPolicyAgent.registry }}/\
      {{ .Values.charts.umsOpenPolicyAgent.repository }}"
  - name: "ums-ldap-server-repo"
    keyring: "../../files/gpg-pubkeys/univention-de.gpg"
    verify: {{ .Values.charts.umsLdapServer.verify }}
    username: {{ env "OD_PRIVATE_REGISTRY_USERNAME" | quote }}
    password: {{ env "OD_PRIVATE_REGISTRY_PASSWORD" | quote }}
    oci: true
    url: "{{ .Values.global.helmRegistry | default .Values.charts.umsLdapServer.registry }}/\
      {{ .Values.charts.umsLdapServer.repository }}"
  - name: "ums-ldap-notifier-repo"
    keyring: "../../files/gpg-pubkeys/univention-de.gpg"
    verify: {{ .Values.charts.umsLdapNotifier.verify }}
    username: {{ env "OD_PRIVATE_REGISTRY_USERNAME" | quote }}
    password: {{ env "OD_PRIVATE_REGISTRY_PASSWORD" | quote }}
    oci: true
    url: "{{ .Values.global.helmRegistry | default .Values.charts.umsLdapNotifier.registry }}/\
      {{ .Values.charts.umsLdapNotifier.repository }}"
  - name: "ums-udm-rest-api-repo"
    keyring: "../../files/gpg-pubkeys/univention-de.gpg"
    verify: {{ .Values.charts.umsUdmRestApi.verify }}
    username: {{ env "OD_PRIVATE_REGISTRY_USERNAME" | quote }}
    password: {{ env "OD_PRIVATE_REGISTRY_PASSWORD" | quote }}
    oci: true
    url: "{{ .Values.global.helmRegistry | default .Values.charts.umsUdmRestApi.registry }}/\
      {{ .Values.charts.umsUdmRestApi.repository }}"
  - name: "ums-stack-data-ums-repo"
    keyring: "../../files/gpg-pubkeys/univention-de.gpg"
    verify: {{ .Values.charts.umsStackDataUms.verify }}
    username: {{ env "OD_PRIVATE_REGISTRY_USERNAME" | quote }}
    password: {{ env "OD_PRIVATE_REGISTRY_PASSWORD" | quote }}
    oci: true
    url: "{{ .Values.global.helmRegistry | default .Values.charts.umsStackDataUms.registry }}/\
      {{ .Values.charts.umsStackDataUms.repository }}"
  - name: "ums-stack-data-swp-repo"
    keyring: "../../files/gpg-pubkeys/univention-de.gpg"
    verify: {{ .Values.charts.umsStackDataSwp.verify }}
    username: {{ env "OD_PRIVATE_REGISTRY_USERNAME" | quote }}
    password: {{ env "OD_PRIVATE_REGISTRY_PASSWORD" | quote }}
    oci: true
    url: "{{ .Values.global.helmRegistry | default .Values.charts.umsStackDataSwp.registry }}/\
      {{ .Values.charts.umsStackDataSwp.repository }}"
  - name: "ums-portal-server-repo"
    keyring: "../../files/gpg-pubkeys/univention-de.gpg"
    verify: {{ .Values.charts.umsPortalServer.verify }}
    username: {{ env "OD_PRIVATE_REGISTRY_USERNAME" | quote }}
    password: {{ env "OD_PRIVATE_REGISTRY_PASSWORD" | quote }}
    oci: true
    url: "{{ .Values.global.helmRegistry | default .Values.charts.umsPortalServer.registry }}/\
      {{ .Values.charts.umsPortalServer.repository }}"
  - name: "ums-notifications-api-repo"
    keyring: "../../files/gpg-pubkeys/univention-de.gpg"
    verify: {{ .Values.charts.umsNotificationsApi.verify }}
    username: {{ env "OD_PRIVATE_REGISTRY_USERNAME" | quote }}
    password: {{ env "OD_PRIVATE_REGISTRY_PASSWORD" | quote }}
    oci: true
    url: "{{ .Values.global.helmRegistry | default .Values.charts.umsNotificationsApi.registry }}/\
      {{ .Values.charts.umsNotificationsApi.repository }}"
  - name: "ums-portal-listener-repo"
    keyring: "../../files/gpg-pubkeys/univention-de.gpg"
    verify: {{ .Values.charts.umsPortalListener.verify }}
    username: {{ env "OD_PRIVATE_REGISTRY_USERNAME" | quote }}
    password: {{ env "OD_PRIVATE_REGISTRY_PASSWORD" | quote }}
    oci: true
    url: "{{ .Values.global.helmRegistry | default .Values.charts.umsPortalListener.registry }}/\
      {{ .Values.charts.umsPortalListener.repository }}"
  - name: "ums-portal-frontend-repo"
    keyring: "../../files/gpg-pubkeys/univention-de.gpg"
    verify: {{ .Values.charts.umsPortalFrontend.verify }}
    username: {{ env "OD_PRIVATE_REGISTRY_USERNAME" | quote }}
    password: {{ env "OD_PRIVATE_REGISTRY_PASSWORD" | quote }}
    oci: true
    url: "{{ .Values.global.helmRegistry | default .Values.charts.umsPortalFrontend.registry }}/\
      {{ .Values.charts.umsPortalFrontend.repository }}"
  - name: "ums-umc-gateway-repo"
    keyring: "../../files/gpg-pubkeys/univention-de.gpg"
    verify: {{ .Values.charts.umsUmcGateway.verify }}
    username: {{ env "OD_PRIVATE_REGISTRY_USERNAME" | quote }}
    password: {{ env "OD_PRIVATE_REGISTRY_PASSWORD" | quote }}
    oci: true
    url: "{{ .Values.global.helmRegistry | default .Values.charts.umsUmcGateway.registry }}/\
      {{ .Values.charts.umsUmcGateway.repository }}"
  - name: "ums-umc-server-repo"
    keyring: "../../files/gpg-pubkeys/univention-de.gpg"
    verify: {{ .Values.charts.umsUmcServer.verify }}
    username: {{ env "OD_PRIVATE_REGISTRY_USERNAME" | quote }}
    password: {{ env "OD_PRIVATE_REGISTRY_PASSWORD" | quote }}
    oci: true
    url: "{{ .Values.global.helmRegistry | default .Values.charts.umsUmcServer.registry }}/\
      {{ .Values.charts.umsUmcServer.repository }}"
  - name: "ums-selfservice-listener-repo"
    keyring: "../../files/gpg-pubkeys/univention-de.gpg"
    verify: {{ .Values.charts.umsSelfserviceListener.verify }}
    username: {{ env "OD_PRIVATE_REGISTRY_USERNAME" | quote }}
    password: {{ env "OD_PRIVATE_REGISTRY_PASSWORD" | quote }}
    oci: true
    url: "{{ .Values.global.helmRegistry | default .Values.charts.umsSelfserviceListener.registry }}/\
      {{ .Values.charts.umsSelfserviceListener.repository }}"
  - name: "ums-provisioning-repo"
    keyring: "../../files/gpg-pubkeys/univention-de.gpg"
    verify: {{ .Values.charts.umsProvisioning.verify }}
    username: {{ env "OD_PRIVATE_REGISTRY_USERNAME" | quote }}
    password: {{ env "OD_PRIVATE_REGISTRY_PASSWORD" | quote }}
    oci: true
    url: "{{ .Values.global.helmRegistry | default .Values.charts.umsProvisioning.registry }}/\
      {{ .Values.charts.umsProvisioning.repository }}"

  # Univention Keycloak Extensions
  - name: "ums-keycloak-extensions-repo"
    username: {{ env "OD_PRIVATE_REGISTRY_USERNAME" | quote }}
    password: {{ env "OD_PRIVATE_REGISTRY_PASSWORD" | quote }}
    oci: true
    url: "{{ .Values.global.helmRegistry | default .Values.charts.umsKeycloakExtensions.registry }}/\
      {{ .Values.charts.umsKeycloakExtensions.repository }}"
  # Univention Keycloak
  - name: "ums-keycloak-repo"
    keyring: "../../files/gpg-pubkeys/souvap-univention-de.gpg"
    verify: {{ .Values.charts.umsKeycloak.verify }}
    username: {{ env "OD_PRIVATE_REGISTRY_USERNAME" | quote }}
    password: {{ env "OD_PRIVATE_REGISTRY_PASSWORD" | quote }}
    oci: true
    url: "{{ .Values.global.helmRegistry | default .Values.charts.umsKeycloak.registry }}/\
      {{ .Values.charts.umsKeycloak.repository }}"
  - name: "ums-keycloak-bootstrap-repo"
    keyring: "../../files/gpg-pubkeys/souvap-univention-de.gpg"
    verify: {{ .Values.charts.umsKeycloakBootstrap.verify }}
    username: {{ env "OD_PRIVATE_REGISTRY_USERNAME" | quote }}
    password: {{ env "OD_PRIVATE_REGISTRY_PASSWORD" | quote }}
    oci: true
    url: "{{ .Values.global.helmRegistry | default .Values.charts.umsKeycloakBootstrap.registry }}/\
      {{ .Values.charts.umsKeycloakBootstrap.repository }}"
  - name: "opendesk-keycloak-bootstrap-repo"
    keyring: "../../files/gpg-pubkeys/opencode.gpg"
    verify: {{ .Values.charts.opendeskKeycloakBootstrap.verify }}
    username: {{ env "OD_PRIVATE_REGISTRY_USERNAME" | quote }}
    password: {{ env "OD_PRIVATE_REGISTRY_PASSWORD" | quote }}
    oci: true
    url: "{{ .Values.global.helmRegistry | default .Values.charts.opendeskKeycloakBootstrap.registry }}/\
      {{ .Values.charts.opendeskKeycloakBootstrap.repository }}"
  # VMWare Bitnami
  # Source: https://github.com/bitnami/charts/
  - name: "nginx-repo"
    keyring: "../../files/gpg-pubkeys/opencode.gpg"
    verify: {{ .Values.charts.nginx.verify }}
    username: {{ env "OD_PRIVATE_REGISTRY_USERNAME" | quote }}
    password: {{ env "OD_PRIVATE_REGISTRY_PASSWORD" | quote }}
    oci: true
    url: "{{ .Values.global.helmRegistry | default .Values.charts.nginx.registry }}/\
      {{ .Values.charts.nginx.repository }}"

releases:
  - name: "ums-keycloak"
    chart: "ums-keycloak-repo/{{ .Values.charts.umsKeycloak.name }}"
    version: "{{ .Values.charts.umsKeycloak.version }}"
    values:
      - "values-ums-keycloak.yaml.gotmpl"
    installed: {{ .Values.univentionManagementStack.enabled }}
    timeout: 900

  - name: "ums-keycloak-extensions"
    chart: "ums-keycloak-extensions-repo/{{ .Values.charts.umsKeycloakExtensions.name }}"
    version: "{{ .Values.charts.umsKeycloakExtensions.version }}"
    values:
      - "values-ums-keycloak-extensions.yaml.gotmpl"
    needs:
      - "ums-keycloak"
    installed: {{ .Values.univentionManagementStack.enabled }}
    timeout: 900

  - name: "ums-keycloak-bootstrap"
    chart: "ums-keycloak-bootstrap-repo/{{ .Values.charts.umsKeycloakBootstrap.name }}"
    version: "{{ .Values.charts.umsKeycloakBootstrap.version }}"
    values:
      - "values-ums-keycloak-bootstrap.yaml.gotmpl"
    needs:
      - "ums-keycloak"
    installed: {{ .Values.univentionManagementStack.enabled }}
    timeout: 900

  - name: "opendesk-keycloak-bootstrap"
    chart: "opendesk-keycloak-bootstrap-repo/{{ .Values.charts.opendeskKeycloakBootstrap.name }}"
    version: "{{ .Values.charts.opendeskKeycloakBootstrap.version }}"
    values:
      - "values-opendesk-keycloak-bootstrap.yaml.gotmpl"
    needs:
      - "ums-keycloak-bootstrap"
    installed: {{ .Values.univentionManagementStack.enabled }}
    timeout: 900

  - name: "ums-stack-gateway"
    chart: "nginx-repo/{{ .Values.charts.nginx.name }}"
    version: "{{ .Values.charts.nginx.version }}"
    values:
      - "values-ums-stack-gateway.yaml.gotmpl"
    installed: {{ .Values.univentionManagementStack.enabled }}
    timeout: 900

  - name: "ums-ldap-server"
    chart: "ums-ldap-server-repo/{{ .Values.charts.umsLdapServer.name }}"
    version: "{{ .Values.charts.umsLdapServer.version }}"
    values:
      - "values-common.yaml.gotmpl"
      - "values-ldap-server.yaml.gotmpl"
    installed: {{ .Values.univentionManagementStack.enabled }}
    timeout: 900

  - name: "ums-ldap-notifier"
    chart: "ums-ldap-notifier-repo/{{ .Values.charts.umsLdapNotifier.name }}"
    version: "{{ .Values.charts.umsLdapNotifier.version }}"
    values:
      - "values-common.yaml.gotmpl"
      - "values-ldap-notifier.yaml.gotmpl"
    installed: {{ .Values.univentionManagementStack.enabled }}
    timeout: 900

  - name: "ums-udm-rest-api"
    chart: "ums-udm-rest-api-repo/{{ .Values.charts.umsUdmRestApi.name }}"
    version: "{{ .Values.charts.umsUdmRestApi.version }}"
    values:
      - "values-common.yaml.gotmpl"
      - "values-udm-rest-api.yaml.gotmpl"
    installed: {{ .Values.univentionManagementStack.enabled }}
    timeout: 900

  - name: "ums-stack-data-ums"
    chart: "ums-stack-data-ums-repo/{{ .Values.charts.umsStackDataUms.name }}"
    version: "{{ .Values.charts.umsStackDataUms.version }}"
    values:
      - "values-common.yaml.gotmpl"
      - "values-stack-data-ums.yaml.gotmpl"
    installed: {{ .Values.univentionManagementStack.enabled }}
    timeout: 900

  - name: "ums-stack-data-swp"
    chart: "ums-stack-data-swp-repo/{{ .Values.charts.umsStackDataSwp.name }}"
    version: "{{ .Values.charts.umsStackDataSwp.version }}"
    values:
      - "values-common.yaml.gotmpl"
      - "values-stack-data-swp.yaml.gotmpl"
    installed: {{ .Values.univentionManagementStack.enabled }}
    timeout: 900

  - name: "ums-portal-server"
    chart: "ums-portal-server-repo/{{ .Values.charts.umsPortalServer.name }}"
    version: "{{ .Values.charts.umsPortalServer.version }}"
    values:
      - "values-common.yaml.gotmpl"
      - "values-portal-server.yaml.gotmpl"
    installed: {{ .Values.univentionManagementStack.enabled }}
    timeout: 900

  - name: "ums-notifications-api"
    chart: "ums-notifications-api-repo/{{ .Values.charts.umsNotificationsApi.name }}"
    version: "{{ .Values.charts.umsNotificationsApi.version }}"
    values:
      - "values-common.yaml.gotmpl"
      - "values-notifications-api.yaml.gotmpl"
    installed: {{ .Values.univentionManagementStack.enabled }}
    timeout: 900

  - name: "ums-portal-listener"
    chart: "ums-portal-listener-repo/{{ .Values.charts.umsPortalListener.name }}"
    version: "{{ .Values.charts.umsPortalListener.version }}"
    values:
      - "values-common.yaml.gotmpl"
      - "values-portal-listener.yaml.gotmpl"
    installed: {{ .Values.univentionManagementStack.enabled }}
    timeout: 900

  - name: "ums-portal-frontend"
    chart: "ums-portal-frontend-repo/{{ .Values.charts.umsPortalFrontend.name }}"
    version: "{{ .Values.charts.umsPortalFrontend.version }}"
    values:
      - "values-common.yaml.gotmpl"
      - "values-portal-frontend.yaml.gotmpl"
    installed: {{ .Values.univentionManagementStack.enabled }}
    timeout: 900

  - name: "ums-umc-gateway"
    chart: "ums-umc-gateway-repo/{{ .Values.charts.umsUmcGateway.name }}"
    version: "{{ .Values.charts.umsUmcGateway.version }}"
    values:
      - "values-common.yaml.gotmpl"
      - "values-umc-gateway.yaml.gotmpl"
    installed: {{ .Values.univentionManagementStack.enabled }}
    timeout: 900

  - name: "ums-umc-server"
    chart: "ums-umc-server-repo/{{ .Values.charts.umsUmcServer.name }}"
    version: "{{ .Values.charts.umsUmcServer.version }}"
    values:
      - "values-common.yaml.gotmpl"
      - "values-umc-server.yaml.gotmpl"
    installed: {{ .Values.univentionManagementStack.enabled }}
    timeout: 900

  - name: "ums-selfservice-listener"
    chart: "ums-selfservice-listener-repo/{{ .Values.charts.umsSelfserviceListener.name }}"
    version: "{{ .Values.charts.umsSelfserviceListener.version }}"
    values:
      - "values-common.yaml.gotmpl"
      - "values-selfservice-listener.yaml.gotmpl"
    installed: {{ .Values.univentionManagementStack.enabled }}
    timeout: 900

  - name: "ums-provisioning"
    chart: "ums-provisioning-repo/{{ .Values.charts.umsProvisioning.name }}"
    version: "{{ .Values.charts.umsProvisioning.version }}"
    values:
      - "values-common.yaml.gotmpl"
      - "values-provisioning.yaml.gotmpl"
    installed: {{ .Values.univentionManagementStack.enabled }}
    timeout: 900

  - name: "ums-provisioning-udm-listener"
    chart: "ums-provisioning-repo/{{ .Values.charts.umsProvisioningUdmListener.name }}"
    version: "{{ .Values.charts.umsProvisioningUdmListener.version }}"
    values:
      - "values-common.yaml.gotmpl"
      - "values-provisioning-udm-listener.yaml.gotmpl"
    installed: {{ .Values.univentionManagementStack.enabled }}
    timeout: 900

  - name: "ums-guardian-management-api"
    chart: "ums-guardian-management-api-repo/{{ .Values.charts.umsGuardianManagementApi.name }}"
    version: "{{ .Values.charts.umsGuardianManagementApi.version }}"
    values:
      - "values-common.yaml.gotmpl"
      - "values-guardian-management-api.yaml.gotmpl"
    installed: {{ .Values.univentionManagementStack.enabled }}
    timeout: 900

  - name: "ums-guardian-management-ui"
    chart: "ums-guardian-management-ui-repo/{{ .Values.charts.umsGuardianManagementUi.name }}"
    version: "{{ .Values.charts.umsGuardianManagementUi.version }}"
    values:
      - "values-common.yaml.gotmpl"
      - "values-guardian-management-ui.yaml.gotmpl"
    installed: {{ .Values.univentionManagementStack.enabled }}
    timeout: 900

  - name: "ums-guardian-authorization-api"
    chart: "ums-guardian-authorization-api-repo/{{ .Values.charts.umsGuardianAuthorizationApi.name }}"
    version: "{{ .Values.charts.umsGuardianAuthorizationApi.version }}"
    values:
      - "values-common.yaml.gotmpl"
      - "values-guardian-authorization-api.yaml.gotmpl"
    installed: {{ .Values.univentionManagementStack.enabled }}
    timeout: 900

  - name: "ums-open-policy-agent"
    chart: "ums-open-policy-agent-repo/{{ .Values.charts.umsOpenPolicyAgent.name }}"
    version: "{{ .Values.charts.umsOpenPolicyAgent.version }}"
    values:
      - "values-common.yaml.gotmpl"
      - "values-open-policy-agent.yaml.gotmpl"
    installed: {{ .Values.univentionManagementStack.enabled }}
    timeout: 900

commonLabels:
  deploy-stage: "component-1"
  component: "univention-management-stack"
...
