# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
bases:
  - "../../bases/environments.yaml"
---
repositories:
  # Univention Management Stack
  - name: "ums-repo"
    url: >-
      {{ env "PRIVATE_CHART_REPOSITORY_URL" |
         default "https://gitlab.souvap-univention.de/api/v4/projects/155/packages/helm/stable" }}
  # VMWare Bitnami
  # Source: https://github.com/bitnami/charts/
  - name: "nginx-repo"
    oci: true
    keyring: "../../files/gpg-pubkeys/souvap-univention-de.gpg"
    verify: {{ .Values.charts.nginx.verify }}
    username: "{{ .Values.charts.nginx.username }}"
    password: {{ .Values.charts.nginx.password | quote }}
    url: "{{ .Values.charts.nginx.registry }}/{{ .Values.charts.nginx.repository }}"

releases:
  - name: "ums-stack-gateway"
    chart: "nginx-repo/{{ .Values.charts.nginx.name }}"
    version: "{{ .Values.charts.nginx.version }}"
    values:
      - "values-ums-stack-gateway.gotmpl"
      - "values-ums-stack-gateway.yaml"
    installed: {{ .Values.univentionManagementStack.enabled }}

  - name: "ums-store-dav"
    chart: "ums-repo/{{ .Values.charts.umsStoreDav.name }}"
    version: "{{ .Values.charts.umsStoreDav.version }}"
    values:
      - "values-common.gotmpl"
      - "values-common.yaml"
      - "values-store-dav.gotmpl"
    installed: {{ .Values.univentionManagementStack.enabled }}

  - name: "ums-ldap-server"
    chart: "ums-repo/{{ .Values.charts.umsLdapServer.name }}"
    version: "{{ .Values.charts.umsLdapServer.version }}"
    values:
      - "values-common.gotmpl"
      - "values-common.yaml"
      - "values-ldap-server.gotmpl"
      - "values-ldap-server.yaml"
    installed: {{ .Values.univentionManagementStack.enabled }}

  - name: "ums-ldap-notifier"
    chart: "ums-repo/{{ .Values.charts.umsLdapNotifier.name }}"
    version: "{{ .Values.charts.umsLdapNotifier.version }}"
    values:
      - "values-common.gotmpl"
      - "values-common.yaml"
      - "values-ldap-notifier.gotmpl"
      - "values-ldap-notifier.yaml"
    installed: {{ .Values.univentionManagementStack.enabled }}

  - name: "ums-udm-rest-api"
    chart: "ums-repo/{{ .Values.charts.umsUdmRestApi.name }}"
    version: "{{ .Values.charts.umsUdmRestApi.version }}"
    values:
      - "values-common.gotmpl"
      - "values-common.yaml"
      - "values-udm-rest-api.gotmpl"
      - "values-udm-rest-api.yaml"
    installed: {{ .Values.univentionManagementStack.enabled }}

  - name: "ums-stack-data-ums"
    chart: "ums-repo/{{ .Values.charts.umsStackDataUms.name }}"
    version: "{{ .Values.charts.umsStackDataUms.version }}"
    values:
      - "values-common.gotmpl"
      - "values-common.yaml"
      - "values-stack-data-ums.gotmpl"
      - "values-stack-data-ums.yaml"
    installed: {{ .Values.univentionManagementStack.enabled }}

  - name: "ums-stack-data-swp"
    chart: "ums-repo/{{ .Values.charts.umsStackDataSwp.name }}"
    version: "{{ .Values.charts.umsStackDataSwp.version }}"
    values:
      - "values-common.gotmpl"
      - "values-common.yaml"
      - "values-stack-data-swp.gotmpl"
      - "values-stack-data-swp.yaml"
    installed: {{ .Values.univentionManagementStack.enabled }}

  - name: "ums-portal-server"
    chart: "ums-repo/{{ .Values.charts.umsPortalServer.name }}"
    version: "{{ .Values.charts.umsPortalServer.version }}"
    values:
      - "values-common.gotmpl"
      - "values-common.yaml"
      - "values-portal-server.gotmpl"
      - "values-portal-server.yaml"
    installed: {{ .Values.univentionManagementStack.enabled }}

  - name: "ums-notifications-api"
    chart: "ums-repo/{{ .Values.charts.umsNotificationsApi.name }}"
    version: "{{ .Values.charts.umsNotificationsApi.version }}"
    values:
      - "values-common.gotmpl"
      - "values-common.yaml"
      - "values-notifications-api.gotmpl"
      - "values-notifications-api.yaml"
    installed: {{ .Values.univentionManagementStack.enabled }}

  - name: "ums-portal-listener"
    chart: "ums-repo/{{ .Values.charts.umsPortalListener.name }}"
    version: "{{ .Values.charts.umsPortalListener.version }}"
    values:
      - "values-common.gotmpl"
      - "values-common.yaml"
      - "values-portal-listener.gotmpl"
      - "values-portal-listener.yaml"
    installed: {{ .Values.univentionManagementStack.enabled }}

  - name: "ums-portal-frontend"
    chart: "ums-repo/{{ .Values.charts.umsPortalFrontend.name }}"
    version: "{{ .Values.charts.umsPortalFrontend.version }}"
    values:
      - "values-common.gotmpl"
      - "values-common.yaml"
      - "values-portal-frontend.gotmpl"
      - "values-portal-frontend.yaml"
    installed: {{ .Values.univentionManagementStack.enabled }}

  - name: "ums-umc-gateway"
    chart: "ums-repo/{{ .Values.charts.umsUmcGateway.name }}"
    version: "{{ .Values.charts.umsUmcGateway.version }}"
    values:
      - "values-common.gotmpl"
      - "values-common.yaml"
      - "values-umc-gateway.gotmpl"
      - "values-umc-gateway.yaml"
    installed: {{ .Values.univentionManagementStack.enabled }}

  - name: "ums-umc-server"
    chart: "ums-repo/{{ .Values.charts.umsUmcServer.name }}"
    version: "{{ .Values.charts.umsUmcServer.version }}"
    values:
      - "values-common.gotmpl"
      - "values-common.yaml"
      - "values-umc-server.gotmpl"
      - "values-umc-server.yaml"
    installed: {{ .Values.univentionManagementStack.enabled }}

  - name: "ums-selfservice-listener"
    chart: "ums-repo/{{ .Values.charts.umsSelfserviceListener.name }}"
    version: "{{ .Values.charts.umsSelfserviceListener.version }}"
    values:
      - "values-common.gotmpl"
      - "values-common.yaml"
      - "values-selfservice-listener.gotmpl"
      - "values-selfservice-listener.yaml"
    installed: {{ .Values.univentionManagementStack.enabled }}

commonLabels:
  deploy-stage: "component-1"
  component: "univention-management-stack"
...
