# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
stackDataUms:
  loadDevData: true
  udmApiUrl: "http://ums-udm-rest-api/udm/"
  udmApiUser: "cn=admin"

stackDataContext:
  idpSamlMetadataUrlInternal: null
  umcSamlSchemes: "https"
  # The openDesk configuration brings its own UMC policies.
  installUmcPolicies: false

additionalAnnotations:
  intents.otterize.com/service-name: "ums-stack-data-ums"
...
