# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
stackDataSwp:
  udmApiUser: "cn=admin"
  udmApiUrl: "http://ums-udm-rest-api/udm/"
  loadDevData: true

stackDataContext:
  ldapBase: "dc=swp-ldap,dc=internal"
  oxDefaultContext: "10"
  smtpStartTls: true

additionalAnnotations:
  intents.otterize.com/service-name: "ums-stack-data-swp"
...
