# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
umcServer:
  certPemFile: "/var/secrets/ssl/tls.crt"
  privateKeyFile: "/var/secrets/ssl/tls.key"

extraVolumes:
  - name: "certificates"
    secret:
      secretName: "opendesk-certificates-tls"
  - name: "entrypoint-swp-patches"
    configMap:
      name: "ums-stack-data-swp-umc-server-entrypoint"
      defaultMode: 0555
  - name: "self-service-emails"
    configMap:
      name: "ums-stack-data-swp-self-service-emails"
      defaultMode: 0444
  - name: "attribute-to-group-mapper-hook"
    configMap:
      name: "ums-stack-data-swp-attribute-to-group-mapper-hook"

extraVolumeMounts:
  - name: "certificates"
    mountPath: "/var/secrets/ssl"
  - name: "entrypoint-swp-patches"
    mountPath: "/entrypoint.d/90-customization.sh"
    subPath: "90-customization.sh"
  - name: "self-service-emails"
    mountPath: "/usr/share/univention-self-service/email_bodies"
  - name: "attribute-to-group-mapper-hook"
    mountPath: "/usr/lib/python3/dist-packages/univention/admin/hooks.d/AttributeToGroupMapper.py"
    subPath: "AttributeToGroupMapper.py"
  - name: "attribute-to-group-mapper-hook"
    mountPath: "/usr/share/attribute-to-group-mapper/flag_to_group_mapping.json"
    subPath: "flag_to_group_mapping.json"


...
