# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---

selfserviceListener:
  debugLevel: "4"
  tlsMode: "off"
  umcServerUrl: "http://ums-umc-server"
  umcAdminUser: "default.admin"

...
