# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.sogo.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-sogo-data
  labels:
{{ include "sogo.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.sogo.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.sogo.persistence.size }}
  {{- if .Values.sogo.persistence.storageClass }}
  storageClassName: {{ .Values.sogo.persistence.storageClass }}
  {{- end }}
{{- end }}
