# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sogo.fullname" . }}
  labels:
    {{- include "sogo.labels" . | nindent 4 }}
type: Opaque
stringData:
  oidc-client-secret: {{ .Values.sogo.oidc.clientSecret | default (randAlphaNum 32) | quote }}
  ldap-bind-password: {{ .Values.sogo.ldap.bindPassword | quote }}
  db-password: {{ .Values.sogo.db.password | quote }}
