# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sogo
  labels:
    sogo/server: "true"
{{ include "sogo.labels" . | nindent 4 }}
spec:
  selector:
    sogo/server: "true"
{{ include "sogo.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
