# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
{{- if .Values.sogo.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "sogo.fullname" . }}
  labels:
    {{- include "sogo.labels" . | nindent 4 }}
    {{- if .Values.sogo.monitoring.prometheus.additionalLabels }}
    {{- toYaml .Values.sogo.monitoring.prometheus.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "sogo.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.sogo.monitoring.prometheus.path }}
      interval: {{ .Values.sogo.monitoring.prometheus.scrapeInterval }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
