# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-zammad
  labels:
{{ include "zammad.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.zammad.replicas }}
  selector:
    matchLabels:
      zammad/server: "true"
{{ include "zammad.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        zammad/server: "true"
{{ include "zammad.labels" . | nindent 8 }}
    spec:
      containers:
        - name: zammad
          image: {{ .Values.zammad.image }}:{{ .Values.zammad.tag }}
          command: ["bundle", "exec", "puma"]
          args: ["-b", "tcp://[::]:3000", "-e", "production"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: {{ .Values.zammad.port }}
          env:
            - name: RAILS_ENV
              value: "production"
            - name: RAILS_TRUSTED_PROXIES
              value: "{{ .Release.Name }}-zammad-ingress"
            - name: POSTGRESQL_PORT
              value: "5432"
            - name: POSTGRESQL_HOST
              value: "{{ include "zammad.dbHost" . }}"
            - name: POSTGRESQL_USER
              value: "{{ include "zammad.dbUser" . }}"
            - name: POSTGRESQL_DB
              value: "{{ include "zammad.dbName" . }}"
            - name: POSTGRESQL_PASS
              value: "{{ include "zammad.dbPassword" . }}"
            - name: ELASTICSEARCH_URL
              value: "http://{{ include "zammad.esHost" . }}:{{ include "zammad.esPort" . }}"
            - name: REDIS_URL
              value: "redis://open-webui-redis:6379"
          volumeMounts:
            - name: zammad-data
              mountPath: /opt/zammad/storage
{{- if .Values.extraVolumeMounts }}
{{- toYaml .Values.extraVolumeMounts | nindent 12 }}
{{- end }}
          resources: {{ .Values.zammad.resources | toYaml | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.zammad.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: {{ .Values.zammad.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
      securityContext:
        fsGroup: 1000
      volumes:
        - name: zammad-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-zammad-data
{{- if .Values.extraVolumes }}
{{- toYaml .Values.extraVolumes | nindent 8 }}
{{- end }}
