# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: Apache-2.0
"""
Generate a human-readable markdown report from the JSON audit report.
"""

import json
import sys
from pathlib import Path
from datetime import datetime


def generate_markdown_report(report_file: str, output_file: str = 'improvement-report.md') -> None:
    """Convert JSON report to human-readable markdown."""
    report_path = Path(report_file)
    if not report_path.exists():
        print(f"Report file not found: {report_file}")
        sys.exit(1)

    with open(report_path) as f:
        report = json.load(f)

    lines = [
        "# 🤖 OpenSpec Self-Improvement Report",
        "",
        f"**Generated**: {report.get('timestamp', 'N/A')}",
        f"**Total Gaps**: {report.get('total_gaps', 0)}",
        "",
        "## 📊 Summary",
        "",
        f"| Severity | Count |",
        f"|----------|-------|",
        f"| 🔴 Critical | {report.get('critical_gaps', 0)} |",
        f"| 🟠 High | {report.get('high_gaps', 0)} |",
        f"| 🟡 Medium | {report.get('medium_gaps', 0)} |",
        f"| 🟢 Low | {report.get('low_gaps', 0)} |",
        f"| 🤖 Auto-fixable | {report.get('auto_fixable', 0)} |",
        "",
        "## 📈 Coverage Statistics",
        "",
    ]

    for category, stats in report.get('coverage_stats', {}).items():
        lines.append(f"### {category.title()}")
        lines.append("")
        lines.append("| Metric | Value |")
        lines.append("|--------|-------|")
        for key, value in stats.items():
            lines.append(f"| {key.replace('_', ' ').title()} | {value} |")
        lines.append("")

    gaps = report.get('gaps', [])
    if gaps:
        lines.append("## 🔍 Detailed Gap Analysis")
        lines.append("")
        lines.append(f"Found {len(gaps)} gaps across the OpenSpec:")
        lines.append("")

        for gap in gaps[:50]:
            severity_emoji = {
                'critical': '🔴',
                'high': '🟠',
                'medium': '🟡',
                'low': '🟢'
            }.get(gap.get('severity', 'low'), '⚪')

            lines.append(f"### {severity_emoji} {gap.get('service', 'N/A')} - {gap.get('category', 'N/A')}")
            lines.append("")
            lines.append(f"**File**: `{gap.get('file_path', 'N/A')}`")
            lines.append(f"**Description**: {gap.get('description', 'N/A')}")
            lines.append(f"**Suggestion**: {gap.get('fix_suggestion', 'N/A')}")
            lines.append(f"**Auto-fixable**: {'✅' if gap.get('auto_fixable') else '❌'}")
            lines.append("")

        if len(gaps) > 50:
            lines.append(f"_... and {len(gaps) - 50} more gaps (truncated for brevity)_")
            lines.append("")

    lines.extend([
        "## 🎯 Recommendations",
        "",
        "1. **Address critical gaps immediately** - These violate Fission AI OpenSpec format requirements",
        "2. **Review auto-generated fixes** - The self-improvement agent can create branches with fixes",
        "3. **Schedule regular audits** - Run this pipeline weekly to catch new gaps early",
        "4. **Monitor coverage trends** - Track coverage statistics over time",
        "",
        "---",
        "",
        "🤖 Generated by openDesk Edu Continuous Self-Improvement Agent",
    ])

    output_path = Path(output_file)
    output_path.write_text('\n'.join(lines))
    print(f"Markdown report generated: {output_path}")


if __name__ == '__main__':
    report_file = sys.argv[1] if len(sys.argv) > 1 else 'improvement-report.json'
    output_file = sys.argv[2] if len(sys.argv) > 2 else 'improvement-report.md'
    generate_markdown_report(report_file, output_file)
