# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-self-service-password
  labels:
    self-service-password/server: "true"
{{ include "self-service-password.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      self-service-password/server: "true"
{{ include "self-service-password.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        self-service-password/server: "true"
{{ include "self-service-password.labels" . | nindent 8 }}
    spec:
      containers:
        - name: self-service-password
          image: {{ .Values.selfServicePassword.image }}:{{ .Values.selfServicePassword.tag }}
          ports:
            - containerPort: {{ .Values.selfServicePassword.port }}
          securityContext:
            runAsUser: 33
            runAsGroup: 33
            runAsNonRoot: true
          env:
            - name: LDAP_HOST
              value: {{ .Values.selfServicePassword.ldap.host | quote }}
            - name: LDAP_PORT
              value: {{ .Values.selfServicePassword.ldap.port | quote }}
            - name: LDAP_BASE_DN
              value: {{ .Values.selfServicePassword.ldap.baseDn | quote }}
            - name: LDAP_BIND_DN
              value: {{ .Values.selfServicePassword.ldap.bindDn | quote }}
            - name: LDAP_STARTTLS
              value: {{ .Values.selfServicePassword.ldap.startTls | quote }}
            - name: LDAP_NETWORK_TIMEOUT
              value: {{ .Values.selfServicePassword.ldap.networkTimeout | quote }}
          resources: {{ .Values.selfServicePassword.resources | toYaml | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
