# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: Apache-2.0
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-self-service-password-pdb
  labels:
{{ include "self-service-password.labels" . | nindent 4 }}
spec:
  minAvailable: {{ if .Values.pdb }}{{ .Values.pdb.minAvailable | default 1 }}{{ else }}1{{ end }}
  selector:
    matchLabels:
      self-service-password/server: "true"
{{ include "self-service-password.selectorLabels" . | nindent 6 }}
