images:
  stalwart:
    repository: ghcr.io/opendesk-edu/stalwart
    tag: latest
  opencloud:
    repository: ghcr.io/opendesk-edu/opencloud
    tag: 4.0.3
  typo3:
    repository: ghcr.io/opendesk/typo3
    tag: 13.4.0
  mayan:
    repository: docker.io/mayanedms/mayanedms
    tag: 4.5.0
    pullPolicy: IfNotPresent
  paperless:
    repository: ghcr.io/paperless-ngx/paperless-ngx
    tag: 2.12.0
    pullPolicy: IfNotPresent
