# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
bases:
  - "../../bases/environments.yaml"
---
repositories:
  # XWiki
  # Source: https://github.com/xwiki-contrib/xwiki-helm
  - name: "xwiki-repo"
    oci: {{ .Values.charts.xwiki.oci }}
    username: {{ .Values.charts.xwiki.username | quote }}
    password: {{ .Values.charts.xwiki.password | quote }}
    url: "{{ .Values.global.imageRegistry | default .Values.charts.xwiki.registry }}/{{ .Values.charts.xwiki.repository }}"

releases:
  - name: "xwiki"
    chart: "xwiki-repo/{{ .Values.charts.xwiki.name }}"
    version: "{{ .Values.charts.xwiki.version }}"
    wait: true
    values:
      - "values.yaml.gotmpl"
    installed: {{ .Values.xwiki.enabled }}
    timeout: 900

commonLabels:
  deploy-stage: "component-1"
  component: "xwiki"
...
