#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2024 OpenDesk Edu Team
# SPDX-License-Identifier: Apache-2.0
#
# setup-dev-dns-local.sh - Configure this machine as a dev DNS client
#
# Sets up local DNS forwarding so this machine can resolve dev service
# hostnames (r.opendesk.hrz.uni-marburg.de, etc.) that are NOT available
# via public DNS.
#
# Architecture (v2 - simplified, no tunnel):
#   DNS query → dnsmasq (127.0.0.1:53)
#     ├─ Specific dev hostnames → synthetic A record (192.168.3.201)
#     └─ Everything else → HRZ DNS directly
#
# This replaces the old tunnel-based architecture (SSH → socat → CoreDNS)
# which leaked socat processes and caused NXDOMAIN for valid subdomains
# like portal.opendesk.hrz.uni-marburg.de.
#
# Usage:
#   ./setup-dev-dns-local.sh start    # Start dnsmasq with dev host entries
#   ./setup-dev-dns-local.sh stop     # Stop dnsmasq, restore system DNS
#   ./setup-dev-dns-local.sh status   # Check DNS forwarding status
#
# Requirements:
#   - dnsmasq-base (for dnsmasq binary)
#   - sudo (for dnsmasq + resolvconf configuration)
#
# After setup:
#   - System DNS queries go through local dnsmasq (127.0.0.1:53)
#   - Dev hostnames resolve to the cluster (synthetic records)
#   - Normal DNS still resolves via HRZ DNS
#   - portal.opendesk.hrz.uni-marburg.de and other public hostnames
#     resolve normally from HRZ DNS

set -euo pipefail

# ============================================================
# Configuration
# ============================================================

# Target IP for dev hostnames (HAProxy ingress)
TARGET_IP="192.168.3.201"

# Dev hostnames that are NOT in public DNS and need local resolution.
# These must match the hostEntries in helmfile/charts/dev-dns/values.yaml.
# NOTE: Only include hostnames that DON'T resolve via public DNS.
# Hostnames like portal.*, files.*, chat.* exist in public DNS and MUST NOT be here.
DEV_HOSTNAMES=(
  r.opendesk.hrz.uni-marburg.de
  term.opendesk.hrz.uni-marburg.de
  slides.opendesk.hrz.uni-marburg.de
  collab.opendesk.hrz.uni-marburg.de
  code.opendesk.hrz.uni-marburg.de
  ai.opendesk.hrz.uni-marburg.de
  jupyter.opendesk.hrz.uni-marburg.de
  id.opendesk.hrz.uni-marburg.de
)

# Upstream DNS servers (HRZ)
UPSTREAM_DNS=(
  137.248.1.8
  137.248.1.5
)

# Dnsmasq config
DNSMASQ_CONF="/etc/dnsmasq.d/dev-dns.conf"
DNSMASQ_PID="/tmp/dev-dns-dnsmasq.pid"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; }
step()  { echo -e "${CYAN}[STEP]${NC}  $*"; }

# ============================================================
# Generate dnsmasq config
# ============================================================
generate_config() {
  sudo mkdir -p /etc/dnsmasq.d
  
  cat > /tmp/dev-dns-dnsmasq.conf << 'CONF_HEADER'
# Dev DNS - resolves dev hostnames locally, everything else via HRZ DNS
# Generated by setup-dev-dns-local.sh
bind-interfaces
listen-address=127.0.0.1
no-resolv
cache-size=1000
bogus-priv
CONF_HEADER

  # Add upstream DNS servers
  for dns in "${UPSTREAM_DNS[@]}"; do
    echo "server=${dns}" >> /tmp/dev-dns-dnsmasq.conf
  done

  # Add synthetic A records for dev hostnames (NOT in public DNS)
  # These take priority and bypass upstream DNS entirely.
  echo "" >> /tmp/dev-dns-dnsmasq.conf
  echo "# Dev hostname records (not in public DNS)" >> /tmp/dev-dns-dnsmasq.conf
  for hostname in "${DEV_HOSTNAMES[@]}"; do
    echo "address=/${hostname}/${TARGET_IP}" >> /tmp/dev-dns-dnsmasq.conf
  done

  echo "" >> /tmp/dev-dns-dnsmasq.conf
  echo "# All other *.opendesk.hrz.uni-marburg.de queries fall through" >> /tmp/dev-dns-dnsmasq.conf
  echo "# to upstream HRZ DNS and resolve normally." >> /tmp/dev-dns-dnsmasq.conf

  sudo cp /tmp/dev-dns-dnsmasq.conf "${DNSMASQ_CONF}"
  rm /tmp/dev-dns-dnsmasq.conf
}

# ============================================================
# Actions
# ============================================================

start() {
  info "Starting dev DNS forwarding (v2 - no tunnel)..."

  # Step 1: Generate config
  step "1/3 Generating dnsmasq config..."
  generate_config
  info "Config written to ${DNSMASQ_CONF}"

  # Step 2: Clean up any lingering processes from old v1 setup
  step "2/3 Cleaning up old tunnel processes..."
  # Kill leaked socat processes
  pkill -f "socat.*UDP4-LISTEN:5353" 2>/dev/null || true
  pkill -f "socat.*TCP4:localhost:30537" 2>/dev/null || true
  pkill -f "socat.*TCP4-LISTEN:30537" 2>/dev/null || true
  # Kill SSH tunnel
  pkill -f "ssh.*-L.*30534.*localhost" 2>/dev/null || true
  pkill -f "ssh.*-L.*30537.*localhost" 2>/dev/null || true
  # Kill remote socat (if we can reach the node)
  ssh -i ~/.ssh/id_ed25519_ssh -o StrictHostKeyChecking=no \
    -o ConnectTimeout=3 root@192.168.3.110 \
    "pkill -f 'socat.*TCP4-LISTEN:30537' 2>/dev/null" 2>/dev/null || true
  info "Old tunnel processes cleaned"

  # Step 3: Start dnsmasq
  step "3/3 Starting dnsmasq..."
  sudo pkill dnsmasq 2>/dev/null || true
  sleep 1
  sudo dnsmasq -C "${DNSMASQ_CONF}" --pid-file="${DNSMASQ_PID}" 2>&1
  info "dnsmasq started (PID $(cat "${DNSMASQ_PID}" 2>/dev/null || echo 'unknown'))"

  # Configure system to use local dnsmasq first
  echo "nameserver 127.0.0.1" | sudo tee /etc/resolvconf/resolv.conf.d/head > /dev/null
  sudo resolvconf -u 2>&1 || true
  info "System DNS configured: 127.0.0.1 → dnsmasq → dev records + HRZ upstream"

  # Verify
  echo ""
  verify

  echo ""
  info "Dev DNS is RUNNING."
  info "DNS queries go through dnsmasq (127.0.0.1:53)."
  info "  Dev hostnames (${#DEV_HOSTNAMES[@]} entries) → ${TARGET_IP} (synthetic)"
  info "  portal.opendesk.*, files.opendesk.*, etc. → HRZ DNS (public)"
  info "  Everything else → HRZ DNS"
  echo ""
  info "To stop:  ${0} stop"
  info "To test:  nslookup r.opendesk.hrz.uni-marburg.de"
}

stop() {
  info "Stopping dev DNS..."

  # Stop dnsmasq
  sudo pkill dnsmasq 2>/dev/null && info "dnsmasq stopped" || warn "dnsmasq not running"
  rm -f "${DNSMASQ_PID}"

  # Restore resolvconf head file
  sudo rm /etc/resolvconf/resolv.conf.d/head 2>/dev/null || true
  sudo resolvconf -u 2>&1 || true
  info "System DNS restored (removed 127.0.0.1 forwarder)"

  info "Dev DNS stopped."
}

verify() {
  local all_ok=true

  echo "  Verifying DNS resolution..."

  # Test dev hostnames resolve correctly
  for hostname in "${DEV_HOSTNAMES[@]}"; do
    local result
    result=$(dig @127.0.0.1 "${hostname}" +short 2>&1)
    if [[ "${result}" == "${TARGET_IP}" ]]; then
      echo -e "    ${GREEN}✅${NC} ${hostname} → ${result}"
    else
      echo -e "    ${RED}❌${NC} ${hostname} → ${result:-TIMEOUT} (expected ${TARGET_IP})"
      all_ok=false
    fi
  done

  # Test a public hostname resolves (portal exists in public DNS)
  local portal_result
  portal_result=$(dig @127.0.0.1 portal.opendesk.hrz.uni-marburg.de +short 2>&1)
  if [[ -n "${portal_result}" ]]; then
    echo -e "    ${GREEN}✅${NC} portal.opendesk.hrz.uni-marburg.de → ${portal_result}"
  else
    echo -e "    ${RED}❌${NC} portal.opendesk.hrz.uni-marburg.de → ${portal_result:-TIMEOUT}"
    all_ok=false
  fi

  # Test general internet resolution
  local internet_result
  internet_result=$(dig @127.0.0.1 google.com +short 2>&1)
  if [[ -n "${internet_result}" ]]; then
    echo -e "    ${GREEN}✅${NC} google.com → ${internet_result}"
  else
    echo -e "    ${RED}❌${NC} google.com → ${internet_result:-TIMEOUT}"
    all_ok=false
  fi

  if [[ "${all_ok}" == "true" ]]; then
    echo -e "  ${GREEN}All DNS checks passed.${NC}"
  else
    echo -e "  ${YELLOW}Some DNS checks failed.${NC}"
  fi
}

status() {
  echo "=== Dev DNS Status ==="

  # Check dnsmasq
  local dnsmasq_pid=""
  dnsmasq_pid=$(pgrep -f "dnsmasq.*dev-dns" 2>/dev/null || true)
  if [[ -n "${dnsmasq_pid}" ]]; then
    info "✅ dnsmasq: RUNNING (PID ${dnsmasq_pid})"
  else
    warn "⚠️  dnsmasq: STOPPED"
  fi

  # Check system DNS
  local resolver
  resolver=$(grep "^nameserver" /etc/resolv.conf 2>/dev/null | head -1 | awk '{print $2}')
  if [[ "${resolver}" == "127.0.0.1" ]]; then
    info "✅ System DNS: 127.0.0.1 (local dnsmasq)"
  else
    info "ℹ️  System DNS: ${resolver:-unknown}"
  fi

  echo ""
  verify

  # Also check for any lingering old tunnel processes
  local old_count
  old_count=$(ps aux | grep -c "socat.*UDP4-LISTEN:5353" 2>/dev/null || true)
  if [[ "${old_count}" -gt 0 ]]; then
    warn "⚠️  Found ${old_count} stale socat processes from old v1 setup."
    warn "   Run '${0} stop && ${0} start' to clean up."
  fi
}

# ============================================================
# Main
# ============================================================
case "${1:-help}" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    sleep 1
    start
    ;;
  status)
    status
    ;;
  help|--help|-h)
    echo "Usage: $0 {start|stop|restart|status}"
    echo ""
    echo "Sets up local DNS forwarding for dev hostname resolution."
    echo "v2: Uses synthetic dnsmasq records (no tunnel to cluster)."
    exit 0
    ;;
  *)
    error "Unknown command: $1"
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac
