# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
appVersion: "1.9.9"
description: A Helm chart for Etherpad collaborative editor (test-release)
name: etherpad
type: application
version: 0.1.0
