apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-planka-data
  labels:
{{ include "planka.labels" . | nindent 4 }}
    backup-tier: "b"
    k8up/backup: "true"
spec:
  accessModes:
    - {{ .Values.planka.volumes.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.planka.volumes.data.size }}
  {{- if .Values.planka.volumes.data.storageClass }}
  storageClassName: {{ .Values.planka.volumes.data.storageClass }}
  {{- end }}
