apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-planka-secrets
  labels:
{{ include "planka.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if not .Values.planka.defaultPassword }}
  planka-default-password: {{ randAlphaNum 32 }}
{{- else }}
  planka-default-password: {{ .Values.planka.defaultPassword }}
{{- end }}
{{- if not .Values.planka.secretKey }}
  planka-secret-key: {{ randAlphaNum 64 }}
{{- else }}
  planka-secret-key: {{ .Values.planka.secretKey }}
{{- end }}
{{- if not .Values.planka.oidc.clientSecret }}
  planka-oidc-client-secret: {{ randAlphaNum 32 }}
{{- else }}
  planka-oidc-client-secret: {{ .Values.planka.oidc.clientSecret }}
{{- end }}
