apiVersion: v2
name: self-service-password
description: LTB Self Service Password
type: application
version: 0.1.0
appVersion: "1.6.0"
dependencies:
  - name: common
    repository: file://../common
    version: 0.1.0
