image: ghcr.io/opendesk-edu/self-service-password
tag: "latest@sha256:9735d99b0b45a3187ff4be5ee0ca1b569ea85cfb2428d9f00c309fdaedfd0142"
port: 80
replicas: 1
imagePullPolicy: IfNotPresent
extraEnv: []
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
