# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

depends_on:
  - test

when:
  - event: push
    branch: main
    paths:
      - "helmfile/charts/**"
      - ".releaserc.yaml"
      - ".woodpecker/release.yaml"
      - "scripts/release/**"

steps:
  - name: release
    image: alpine:3.21
    commands:
      - apk add --no-cache git curl python3 py3-pip
      - pip install pyyaml --break-system-packages
      - curl -sL "https://github.com/go-semantic-release/semantic-release/releases/latest/download/semantic-release-linux-amd64" -o /usr/local/bin/semantic-release
      - chmod +x /usr/local/bin/semantic-release
      - git fetch --tags origin
      - git config user.name "openDesk Edu Bot"
      - git config user.email "bot@opendesk.edu"
      - git remote set-url origin "https://opendesk-edu-bot:${GITEA_TOKEN}@codeberg.org/opendesk-edu/opendesk-edu.git"
      - semantic-release
    environment:
      - GITEA_TOKEN=from_secret
      - GITHUB_TOKEN=from_secret
    secrets:
      - gitea_token
      - github_token
