# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
{{ include "etherpad.labels" . | nindent 4 }}
spec:
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
{{ include "etherpad.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
