# SPDX-FileCopyrightText: 2024 Zentrum für Digitale Souveränität der Öffentlichen Verwaltung (ZenDiS) GmbH
# SPDX-License-Identifier: Apache-2.0
---
authentication:
  twoFactor:
    # Define a list of groups to enable 2FA for.
    # Note: Removing a group from the list will not disable 2FA for the removed group.
    groups:
      - "Domain Admins"

externalServices:
  nubus:
    udmRestApi:
      # Enable to make the UDM REST API from the Nubus stack externally available.
      enabled: false
  matrix:
    federation:
      # Disable to not support Matrix federation with your installation.
      enabled: true

admin:
  portal:
    deploymentInformation:
      # Disable to not provide and update openDesk release version and deployment timestamp for admins in the portal.
      enabled: true
...
