# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
# Before increasing the replicas of components, please consult the scaling documentation at "docs/scaling.md" to ensure
# that scaling of the respective component is possible and has the desired effect.
replicas:
  # clamav-simple
  clamav: 1
  # clamav-distributed
  clamd: 1
  collabora: 1
  cryptpad: 1
  dovecot: 1
  element: 1
  # clamav-distributed
  freshclam: 1
  # clamav-distributed
  icap: 1
  intercomService: 1
  jibri: 1
  jicofo: 1
  jitsi: 1
  jitsiKeycloakAdapter: 1
  jvb: 1
  keycloak: 1
  mariadb: 1
  matrixNeoBoardWidget: 1
  matrixNeoChoiceWidget: 1
  matrixNeoDateFixBot: 1
  matrixNeoDateFixWidget: 1
  matrixUserVerificationService: 1
  memcached: 1
  # clamav-distributed
  milter: 1
  minio: 1
  nextcloudApache2: 1
  nextcloudExporter: 1
  nextcloudPHP: 1
  openprojectWeb: 1
  openprojectWorker: 1
  oxConnector: 1
  postfix: 1
  postgres: 1
  redis: 1
  synapse: 1
  synapseWeb: 1
  umsKeycloakExtensionsHandler: 1
  umsKeycloakExtensionsProxy: 1
  umsLdapNotifier: 1
  umsLdapServer: 1
  umsNotificationsApi: 1
  umsPortalFrontend: 1
  umsPortalListener: 1
  umsPortalServer: 1
  umsSelfserviceListener: 1
  umsStackGateway: 1
  umsUdmRestApi: 1
  umsUmcGateway: 1
  umsUmcServer: 1
  wellKnown: 1
  xwiki: 1
...
