secrets:
    cassandra:
        rootPassword: 4YWRhgCpGpNvhJGmdPkG0HT51WFhRz9NMqv60k_5APMP-y5nV-i146HkqNctDroR1rmtCXhu1gXVP-nIHveTGA
        dovecotACLUser: Z2cgsCZzkbhn-GKBFFVl1It-2DNVDLkRHmx99-CJrJVjulFgWwbE-ONYRvXtcH8mifdvtVfoA1IR7lUByliysg
        dovecotDictmapUser: fzglgGJ_i4zRnihLRRrsJHlRDDxBrWLYii86ds2Fnc-dTr5-o6ubU9IXuxTSvuqTXXeKRcGC--R9qs4YfTCyqA
    oxAppSuite:
        adminPassword: Xaj-1MPYdu_vRx-6jcumzYmL-rsnDB06ZaxCyX428UPxSHbZjoneDHjreklHVX0UsqNvO01V1Ks46YGqkMFBSA
        basicAuthPassword: Wg4KPzF3U0B1Dvo08sZOh20BmQIN9ChdgzQyxl55Pcb4CYYGXn9kD3TSp4LK2Wg3kvjXo3PUig-OSzEWVTTYew
        cookieHashSalt: LTJOxU_u5gM7fZhovDk1O59UwyAr3FbD_PawMnemk06XyvRfbmmBIgb5xrSBEuG-FoDIP7euX0ZQw85_XKcr_Q
        hzGroupPassword: kcF0aDh1JCSB-TRx4U18ukUYw2WrgVmrpLiWDbL7E_LHoqgptK8eY-RSQVONKYzs3o69Z7NfBQtWn1ykIL2ytQ
        jolokiaPassword: gCWfserda0bxufiUw7ILKwUx0S5ll4tKHzHPJBY1qT5QOcp4XQpo-yxbNngs_zp4dNPMKoZF-BNKkAaHjD9Vog
        migrationsMasterPassword: B-HrBEsi7Lav5LYfHZfSCXerQ_8M9qjvIgOVhbmR-knQWqjenfx2iK22qo5NHsLljtfYKhGtV8mqkdEe2do6dw
        oxguardMC: MCsw0gqnMuFX0UVssVuTcL9biJIaY
        oxguardRC: RCc3njek3gDzVdvL0QMFxL7lybeBQ
        sessiondEncryptionKey: yiXSmKmI7VfIYUC9JpHqOC38NJZo7QYZ5JWlOy82ePlR2SKLJbDWHejJGWwF_Z8vDC0XYVr4v6x3WZvPlRxh0A
        shareCryptKey: 0MPOsinA-nfl9GhcfzYVSslY1E1cOR2J52re3Tfh_1RT_8gVVrDvI4Tcs_vXFLBcj8_6SJavPkhb5w_v7LijFg
        synapseAsToken: PlQJUaK0KWPD_5OSWHGfjc7vgGXbDHcK36zygf6bwq0UYgDGd_Y-n5mp1X_0g_pzWNsL8drPxgxo88R6Xw4joA
    oxConnector:
        provisioningApiPassword: r5WBnfFvheQwXXp2V_Byy_OE288nw5lHGmhPrF0dy4JqGaWlpuheY1j64z6pD5lJ46YAdmaX22yArN8Ots_lhg
    postfix:
        opendeskSystemPassword: bmG-onuXpevVYMeaNFtdQhqUHyaslT4qLNk97s1a2Sl-XlfIwZVxXBeBQcFoRUGhLEBQd9VCCEMEFGD5a7uvcw
    nubus:
        masterpassword: 7bmXaevoiZ8Qvn7BqsTbRkAFtZ_M6Ux2TKU1qN8c4ApgT-yCNebZa0TvWIOQPHOZZC7Ywy8y8q6FU9dvkvnmPg
        ldapSecret: k6tesG1nOiARvoYi6YqDm51hDAOepgjuzYNARguk1lQrc5tqHRthPF5oYKJiJRjyiPDJ61yBzlMo8UN3VX86gA
        ldapSearch:
            keycloak: 8OXDtLx3DLyzn2IrBG0RxMvnrV-9Mv1WoX0BH3wQqmnEGOqy9_ZwA5Lh-BvletzK2oMHoXBkxEVCeMgsiUpUVA
            nextcloud: bJ4qPi-8LNp1iBqK2uFGrPwzNy9QEMdMce_2PM-Wgc-v_OPqVg3l3OVfCHniKc3ZegR0qD8vzKqpnf4apN-oHg
            dovecot: iukyHh3jcfac5tq_9wYo5RP07tnbxuDyHViLZQZ_71Iqnfy1bay8WfJA7ON1xjY2ROOy8wlduS6HbagOOeo0Uw
            element: 2_g7OuRHYrhuWFdH5WrkTJYpx04XxvAmKrnF1mDy9dyqFgcmO5DDJ5J3v0f52tDFjUkkTE1vLpNliYPsD4FmWw
            ox: uBnIWJaWMYOv_sf7dx4NV_VyyCny2jFwHUNDZ_ZrZmUAlMfZiMwAEdzVc4F9L5FiRKXIew3tSZJ7QXGoGZsZzg
            postfix: tmjJ6J8SHKTYEEfwjLLfahBer3US0hhGPDUTpJbABtjx1qsqP-9EvFkNEgEZDscdI6uJA1Y9gOjaXsYy4jfckA
            openproject: M-W-TMAeebyqx3rr-uUk0qrliHmQzeincRXBKmv-xW-LnPZL7dxNQfeUK7QR58kC1mQNMkKMxjF4-sCGUzkteg
            xwiki: nnjtFO8zcqrs-OgxpXbyi51Do9eGO6Bc7jrJxhmH-G-kwzINYW6N4CVVnZw-Qt7SDqW0cTRCkxnNfVT_o1yMOg
        systemAccounts:
            administratorPassword: lSNzx4nmIuaWZ-RgAkkys8TkisVlQpM3e-82Nlv3n5BhnvMTPXMr_uqPmTE-Qu398k8n_66D_Ct6GCPJS_s6-Q
            sysIdpUserPassword: ehb_yyQlwCBf56wc0l8hj8lPTrOCN369m1sm69boAQ4tMc2PyWbmXe_pmIb-pfkT-lFCgHFHj83Io0YKcgWVug
        portalConsumer:
            provisioningApiPassword: JTmR9D_IUrFP_jPEZ7VMd0pZ5bG6xIPwXRlMQGoHrKqUokgfYLEsQYHIzZ6AFeK_wjpFVSee5cl1nYm_KRCIOw
        selfserviceConsumer:
            provisioningApiPassword: nv-5lQxkVk0kQKc0_D9CPMjkbj4upMv2bOJ0V_ATpsQQz95-l97oBxPanPAtOfKwE4UKfRZkTYYJBNGdtH2-hQ
        provisioning:
            api:
                adminPassword: G_alok_2SZfNY1OFFb1MVSrC_4J6ha0PBdXhoPVYwidIaROllphx55YWffhkVxPEI7uOR_KFTAbeL4nTkn2PeQ
                natsPassword: TVDR1C5FSmVfLB2fK-ncE5cfBU4W7SJQIcdTzWs79flJHTAxnfpDyH_8c2-cuDozUFwEbChp8Y8ru_j-k_0FTQ
                prefillPassword: mOS1dPXzUOyue2EGC42GQxKbvQqRKN2jaWdYwvsxNKMPRxD8SO9u24U28oIWYt-W6aJH3Z3PN6wz-8LjPwYSuA
                udmTransformerPassword: agooFaHaXkwhQ5Itx6GhdnKRLata4HACUlCwUMfFF1SI6caGXiWlUY04ZJAXxS5RucSgI7kYGAcepepbVZaDNg
            dispatcherNatsPassword: n-s9cboHsWZzcN1YLAootCBwU8L8
            prefillNatsPassword: nGc07PPkBqRSb3t9gY6ns43ixDLk
            udmListenerNatsPassword: nHFmiHeG7Gc_tqfK2EtbvXp-42Jk
            udmTransformerNatsPassword: nRYFYCi5HdpfeP-n7ALKOAFARlas
        guardian:
            udmPassword: 96Iab6XC-j40Lqqh0JmnkVLsMMAtqMS0AYcH7njZBf_LvvQ7LMNRMeTz1tPH11pUMZGXb-TP2m9t3NSDyng66g
    nats:
        natsAdminPassword: n94JPpcqzAS83RhCzEEg_9pNsvBI
    postgresql:
        postgresUser: KAQUA3IVpIAmW_5SlIkACRg7mlelFBm6tn6YTPqaDV-J4fQ-RIJdi5xGX8_QC2ctunxNqE9gydsZ7btE-fiJNw
        keycloakUser: MO5A-fNNzso9efnEIX_McTtIbB1TFxqr5Oz1AQHSGV76ETZN4IcSjOu8AeZdXhSbfDbAtBne8yWEVNiqubmlOA
        keycloakExtensionUser: hFqWfFUceXoqZxMaoPo6kpmNBPG3bCO3NZaxOyDp1FbX7MA33QPdZKjUlnBWav30vzve6H5QxGxuPeZO0EhNhg
        matrixUser: FrKDsufYCv1jH-76vCcU8ofAE5qcKq2zJ5J5vCYPd0Oam87eMl5HBkk4Wuy6Nz8dMwZSk3AaIC3JRj-nfjULbA
        nextcloudUser: i3vbo1C6x_kQkaPY0uiw053TOMKsHjUF_lyfQtHJ9GlxRXsvohbgB4K99X6flKURlHw4zJI5JYZj0q-EAgJXCw
        notesUser: 0gULebsCH6ZhnfRvvT64hsupm8nTzcFXazN6A979SolrPPxyJoEKqDbysNK-SaMMOgtIy5ZY5G-ydKvrdSuMqA
        openprojectUser: 6SlVtM0pi3_ePNFfVEzZrlbTgsxuKp6it82uY0yp7aDTdBaG0oNJdcdHwx-6npcVlMKJveVoktOu1ZPvamdYqQ
        umsAuthSessionUser: gOxymCmBEbxV0hWIH1Bk0W86d67TCdSR_Q97AKcRwpmbCrDIl2Q2P4tQZtYYtS26lnz2rHpnNA6KHa4naf5Mzw
        umsNotificationsApiUser: T23lXp-edpK9cYPl1cTcmQUI39vFzEi6IS3Bh4Fv8QRPSVubS07UuwSCATjpuFHQYuyYNEJVVCGgS8yYUaxN3g
        umsGuardianManagementApiUser: zM0wQNtc0aG6xx3h9jPM_NqRi86KqepqMJf_YcpwRGWankk40xBngGsT1IzvybdObRcTSB0tigqawKk6ZQUsjw
        umsSelfserviceUser: Zn2aNHhCyen6vf0qccXS6EE9I-NgAqxLSTBzsrNAFQUEguslufg_BdGYYzsdQ86HS3IpJkIPqvL33eOE-FDpgw
        xwikiUser: vCimROGAzmtFrD7vyffOUhBk8a4etU1cVMq46nqh2NVi6y6kXkNbqJB0WqnqjcRZ9A7CCjwDJxlzlODVvEW9qQ
    mariadb:
        rootPassword: xp8A9jeWKYrKgI5H3UcdckR4i5lbcl8LkvSLy-65Jisv2U_RgPzXlo3Yn1_lSr28pzZ-UgZKdyt-8W1_hzQdWQ
        xwikiUser: q95QB5qyvExBHyNQlU-GRcRuCbvNxJyUvV__i1Ika94fzs_bGwk1B-aIxlVlhMjnpTxTudD09ZGqIFEkUYWxqQ
        openxchangeUser: m6ic_5pobCyRrMIOW1HoAfDcDGmm0lSi9JFBX2UjWWmNDWj9XJZEMu5zFfpnTVzuwu48Kqpx4SiVKvTtj0x9Lg
        nextcloudUser: jU_1niyCyuRKmS8zoj361cuxSrTk5EMI-j7SXAfaDb-CRSajGhv81AC5qX2LTYw8y4phSAwyPZe-yIKHDbuhUg
    minio:
        dovecotUser: k2eqI6uFCTEaGJsGqHjnwU0giDr5rGrbpb7mH12lgnWnR6gdzl-Z2xzWAqAERDcALSndzI-bQ7HXSt0BBW0FPA
        rootPassword: Ks7LLyE3TplBJri-suP9PH_sy9fjbk1DpJDcOZU-JPH3uEM65YR7iLnaK-ngTZNquNsqy-0q2ez3ae5eoyvqng
        migrationsUser: mNsz5gWGkmhrH7i46xga-8DDr6027ofcDngLffB_e9aPWV0pI1xfiOmT2-zFoSMqWoiKXQ6ZFPHpDgXxW1fzTg
        nextcloudUser: YEaFJUhXfy5-ar-V-rc5Qx_vNOJruv9l8M2wmHcE_EzmwpELdd9Kc1FgOIWSE4nAnCOdWg5nvag9lQEkOosPEg
        notesUser: 5Ne07Qryt2etDuL4EuJLoLsyz58XO2AEuHN4bDwSKXypHYBNdpNC6wccn_rzMjI9gJ_pUsgK43K-NvG170Irhw
        openprojectUser: bx_KE_bxp3jAbq6hqKKlO_sbYsx82f19VHM_IOfXrhjH4ST71Q5zsjXuTuMXQK5oXP6Iuvlf4pT-8iySyDl4EQ
        openxchangeUser: wNfCXdJV8VzvaGMJEIuteST9eE3qzu2njimTbVaApS-fKlgNvu0cmyEBlNEooDW_3qp-zBy9ANOn3P2omt2RJA
        umsUser: _bUEhBni3HN2WFz4x9Y5q1lgsmdiCsdGIHDF4UPsWjwNezVIIFCbZo4xtjzR-NXQMYKKtxyis7InTyS3ysTpGQ
    keycloak:
        adminPassword: CVLFyttUeqdBWbxK-oNh2HC3zS3jnymh8w8xgCDezsOQIBumYAgPv8pdrHkHqq65eTmQk4HeO6IK7lFwH0qnhA
        clientSecret:
            portal: 4_R7hhyoMGrYgy3XfSb2sFHLrZga17djZN2Kmqbk6AjA3XnPkWU0eanGWaD8hjLWqJoneH9pxgXRVROejIYo1g
            dovecot: qSL_m-KQ7Pj-m_FhnwsOMu02d5nE0Izk4Qp7rqZt-vqDz-fEHl0OnRF7LEjrGI6Q4vJ45j9eFHaj5PVB2RjRgQ
            intercom: EtpjKZtmSjYIPVsyl1PytABPTHBVhm3-9ryvZg526jAny2gNuZDBZQur5xcq2hdlPAP37gfv5ghkPUDFR7J77g
            matrix: r6XB7QSaRA4T-1cGKc0jt-9afZLs8JpPBHfFtYQXi57CS6srbBb02C5yHIByRsSUC8XcOn4Lr1LOab0njx7-kA
            jitsi: Q17-ZXuaGQpUzzEb2kkxZZg-7Vd1_M7gcG5DtZKR3dcQrMf7AOGU9KO_1sRFZ-OxKWdxq4_9KrmWg8F-4i2geQ
            ncoidc: kZLH_V1Jc9Q5HdwrN5xzXb_e0iBi5NqW3FyZR2p0bgpIwen-s8SisXJimAIC8D9nsqE6qW4GB7mervmY0ynJXg
            openproject: Eo78UkYN8WyGdmVBeFX3yYwsPETrtLVpXykFojOmEMCxN28eYSJIyZgJrXNhuc37NJyCJrL2t1gXpCxSg-x0JA
            xwiki: Zuz_QV7Kw7ds6crN1FkXDKceJ3uYPITtbxODUL5Wm9vsFEnqbym7TFJ9SmIj9nyljTK1xeyONkWEGCegLthBAQ
            as8oidc: 7F8ADzRpI6f_rB8qn-KsKzxoYlv2S5C2dLHVYRXEFoPKvttY2_CeGykripl34d-I0xGNxlKZohyZEaBnnaJrog
            guardian: pksMFZJ3AKUSFpPXbgXXMkZTy2ZJZAcsEFO8Pko0PH3dQPKzZLV8c3kYpivcG0LsHf3SNoP3g8-p3w9HjBBmgw
            notes: fHZ0qT1S5vOHmup2Vi24hicZn2KkVhATJvv1OmUgelAa8ZYjA8s3vpARUfTiKo0RUD5ZGT1ZvHBdW4IuIm-64Q
    nextcloud:
        adminPassword: Ge_9MejayXb4hyzT98haBYbXZoYiXPIaDyqXFCrRvv9QCqbE6D68dQWEC7UurpeqjzuuSP8IB0pG6FtYkUtHdA
        metricsToken: 3Nxbg2h0QTh-XIENhl6MdaW_mT_nTr9iS-4bClWMcAp5TZoVaSkC_8eEsBBkCDwqhU41iIZi7DRGZlDAffaSdQ
        statusPassword: nW6iRQsQzcaSEGOvWg9V8A4Efk20W-BUOzb0UeNtoInNN5rUOtg6bAKgmvSoCKs2R1EpI_-zxQzKjqahZFi2LQ
    openproject:
        adminPassword: H8t7iHUW821OYhaVWYWBOZcepvFDWHXejYq6BsBmvzfUNp-eA5KthRARstVfFy_S3z3l2Qkzzw6U2genC23PjA
        apiAdminUsername: jEw70HLFS1kXokj267ffHVLxyrh3KWAo33bvv1d5aqSOdzCAJ9Yz0gqh4UzFDL-I1OQhBMfUGBMGMgyIymEf2w
        apiAdminPassword: t_eGgc_svk_1s6p4Q4zzHlxYlNdyHNlO-T_1YcgSP-9WOjFZpHYLrqgSguJzgFj4KlvoSeU6-7KLsNteUQtAfg
    collabora:
        adminPassword: cVpZTV5P4lwR5zFpBkssognWl901nHU7ub32A0uQehlm4BKX9YJ5strf_91epG6HlxrH-0XZIUyv1OgYeK0UFw
    jitsi:
        jwtAppSecret: 27gAuhyfQp9e2gHXviPIn9KYejlVHyaGxtuVba1Z3tBRH_y1PwpdufeSPvT7VIP6CD4oca3F-WPZ7dm2GWZ6dA
        jibriRecorderPassword: N16BlfncxAJdV99KrwFuRAmntc1j5fVTW6uQO4bfOyLyRt3owPuO1P0YTsmFhdx7y1VObt-Lutkq3hcWXxqPNg
        jibriXmppPassword: cCUL3Jr16Y1W4pJG0dfDiWBTxz-sFszcgOvknbzEpRB7S3xwpPbNbLQygQFyhlMHuRAP92P0ZMJweYo20aZEug
        jicofoAuthPassword: BzelOrQVcz8K4xO8S5oQMcrZYtz6udNdjxsUV4IweG1VdI0TvpZOtWTFJnBLht_boeUCOuiBVvG5hpb7aQAarA
        jicofoComponentPassword: SMmubi0jRfh5gjjEc6JwMmciC3sT0DwIwVL5SW6srjz5mdDC9jX2PUVeG6a1kQiBGqa_DhrxfNDkU8bn47f69Q
        jigasiXmppPassword: CldyKxJGrE6BRz2SsGyhS2vINzm_Woi3ztcUK4MApl2YgkPEyM7kk9KJO-Y4189y7Hon4ToCz9RiUie7QHQR4w
        jvbAuthPassword: oekNeFU7g2CGcM50m0dMgAqEfZHQQHhvzUBFUQslNSOIRVN_5yASaEHLtG73KrocuaiHNaE9lw3LXjUXa46c-A
    whiteboard:
        apiKey: pG7uyQbnoRcNtm7DHrzFcyXiuhd2qoaIRDyb0APgjOYRnioEj_Mhu_Z4lMLliOyIhgI2gegqf2WY08A-ilcHPw
    centralnavigation:
        apiKey: U6Fa48q0lyfnjlbuUpRytmSdiNVVc5N6fZoAx1qNHjY1GxT4KjPjMgs4WiL0BWGmV0KLN0urfRHZZxP8EmIwSA
    redis:
        password: CrYoYXluDcp8obC14MAVzXelNs83zKZnjVHU4CNQkQuoJYbKhhuL9nG_H_kXNrnDqTI-QDJLy-U42NZakHHaag
    dovecot:
        doveadm: KGZUObkgs4E-fWTXSDo27YSv6ZUrYFifCmzn9YAfD85R8ZNvoOnf-BjADT1_TR6PaBYSzzSqdF_3UCVZVzRcHw
        sharedMailboxesMasterPassword: QU966qVtRWet3k8LCkdtaSM3a5D10kYkveVQIveQxDgaXquQqUtA-vGkaPVb7F9xlJiM7bVF0ILai0s2ke7WrQ
    xwiki:
        superadminpassword: ZmsNNwxHZaJ4NdfSuJ-P3CbmhXX6oTgWlVmf0ZA-ZxlPq9Mg_G63Uk8Dwo2_JdWsNYMeby4AfV_BdtIGTI3MXg
    intercom:
        secret: Mjhd-dw1jBL41PvcfCQgf0sipZO8IHl918K4eGpNs4AFnhhFQTTbqISWyYYDbKrqipwo6yQbW3clgCNnTQzGCA
        synapseAsToken: -6wImRPzLsDJub75Cu6Y7Flwzmy_5lOxnLWaEw30mQmJX_30e5g7LxnX2N-XSxPDp_UbuL4SHNiANhlmjIYtiQ
    matrixAdminBot:
        backupPassphrase: ebEhBnLLeHeyElnIw_4z5XcyT4NYf7z1-yFuwH7nf7p_eMFBITSsC0HRGBzGYvtRWhVf33S_UL0JHDFJDZAlVw
        password: yZe0ndvmoyeGETqBBD6ywoZ2pLlIluFkXqXo05_SKdLmrRPvznZHlbZIeJ08ko-7vwyn9xOCLmhdMw9odhIjBA
        synapseAsToken: pnNzxlVJqoLV1C1QF3iaaapKX8ZbQiseFXOUZBroQ-UzyosJWOUaZJHAI88YJ1LVr5um8b8_1ePSoIAs69d_Iw
    matrixAuditBot:
        backupPassphrase: V_bjpiJL5jtS3Y_qrOVgzRa2rt3l8yMcdsrDsA0uPs61TM1tAMQwvTbYwyaexanpVnSaEGOVjMAiidMihbBkWw
        password: 6OWtg9D1IPwkPzZusaE2-hlohWM7JEF2g1G0GftQRE734bk42_7dnwaXED20OUSaYYyBMUXjWvU6zCQBd_dxFg
        synapseAsToken: VKHLOLJ0eUjosliZ6pMFNemTWCO0q2GkekhX9ZM0dceDiuKKYX6gWTggpzp4MtTAS90I6aS2Qd6Q2eLP7q7edw
    matrixGroupsync:
        synapseAsToken: ss7VMNTK_c1UsfDXNG4UXE53tmZlKLlFeWIUu7bPOlFtto5NZKeAK2fcYLIbPXcQieXUnRG07W7JM_oXZ8LWOA
    matrixNeoDateFixBot:
        password: oXcHZUWqEZc3b_4LBtcpYnZilKTRdN3PrwWgTU0wUhgsAd4c3P12qbZEo6FpcoMYGgmoEJZvz7zfFGfn4HnLNw
    matrixUserVerificationService:
        password: WjNFMaCSTsaa_yYW78TxNdiDZCzBAv_GWr34kiKuSBCD-NYK3rrwJBfEp6V3ub5j7Xjwo4AiXgYmz1P8hCzpLQ
    synapse:
        registrationSharedSecret: PymMROiW_Blj9hTzh_K_pg0ltmB6E55ZGjC8HBdVr4n-qPr6CbF7o4o9MrTDkLkQIDzIWPpIg6GGuWR1N9CLWg
    certificates:
        password: jQK4p33r9H65PQuyMC2hB1Fr0f1IuFUXhQuAiU8D00JQgxoKK_Dt_nT8SxCBhCv5Mie2-Eo1J4UO0vMqlfu5wg
    notes:
        djangoSecretKey: YHX1m4mMXqUUdhk3FtPuTE3HlPoojnvD9S43jaiBOu4z5c1tyFQYycwBffnkQihZj6kTDBmnwNQzvJc6W4a_Qg
        superuser: THDUhUE49SbwquWxDvj-DMQUX_sG5LKmMUbus1vIaiakbMoRoq5sFyutCjunvlQBwfUCFdJWmNP217PbxJPcUQ
        collaborationSecret: CMHzgzt4eOIKPFhiAsmP5QUw6wU5ZG2cPq1jnU_DrPTYBgDXsdKC9wYXMbpc3Z4Lf9lH7y5StbsqK2ERWyypsg
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zw40j4ax88ljk032zyd7yjr707ejce5ps5nlxmgld6ynwswnc2qcat04y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNFYyVlRIblQ0YmpBU05M
            aGN4MExPVlNTMDRWZEo4VkVzdVNLK1FQVUNnCjI5NERjcnhSY0NxcXBLOVRqMExT
            cXZ2ZE1nRVpIT2M3NXdWZ3N6V2NnNDgKLS0tIDZlTzM0dUJMWlU4SStobHY2RGRk
            MU9EcVVvdmZYRGovZzZYQWxzTFduU0EKuJaixjZlfH15mDPH/onhdUVmyU/TL/O6
            sP69xZiIN2qZbK51odPSjCe9rHMB8eiTOjzpo+tkqCH9Csh79QVhMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T05:34:17Z"
    mac: ENC[AES256_GCM,data:eoooys36VkqdLeUBH5Qxlgbm1wB7P6c6bqEFVk53Tk84wXYD4CkXNt35GhjAcr13T7DgW0Ju9kFA+IMWU0VtqW7lVUcKV5yS7LJr1BiLZSfVStpgt+T8J/e6ovYKd/xBgnttoV25JKr2gBOM2qv6IjUENUir6Z4pL0rzp6vpjDk=,iv:rkwCGDt0tPAvbvLfqmcHtkUUxdD5s7RYYWWy4C8FEBg=,tag:1XLJ8FAGiK1brUjqb8sR5A==,type:str]
    pgp: []
    encrypted_regex: ^(?!secrets$)
    version: 3.9.4
