# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: Apache-2.0
{{- $secretName := include "mayan-edms.oidcSecret" . -}}
{{- $redisSecretName := include "mayan-edms.redisSecret" . -}}
{{- $databaseSecretName := include "mayan-edms.databaseSecret" . -}}
{{- $emailSecretName := include "mayan-edms.emailSecret" . -}}

{{- if not .Values.mayan.oidc.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "mayan-edms.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-secret: {{ .Values.mayan.oidc.clientSecret | default (randAlphaNum 64) | quote }}
  secret-key: {{ .Values.mayan.secretKey | default (randAlphaNum 64) | quote }}
---
{{- end -}}

{{- if not .Values.mayan.redis.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $redisSecretName }}
  labels:
    {{- include "mayan-edms.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ .Values.mayan.redis.password | default (randAlphaNum 32) | quote }}
---
{{- end -}}

{{- if not .Values.mayan.database.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $databaseSecretName }}
  labels:
    {{- include "mayan-edms.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgresql-password: {{ .Values.mayan.database.password | default (randAlphaNum 32) | quote }}
---
{{- end -}}

{{- if not .Values.mayan.email.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $emailSecretName }}
  labels:
    {{- include "mayan-edms.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.mayan.email.username | default "" | quote }}
  password: {{ .Values.mayan.email.password | default "" | quote }}
{{- end -}}
