# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.grommunio.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "grommunio.fullname" . }}-pdb
  labels:
{{ include "grommunio.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.grommunio.pdb.minAvailable }}
  selector:
    matchLabels:
{{ include "grommunio.selectorLabels" . | nindent 6 }}
{{- end }}
