# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
{{- if .Values.grommunio.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "grommunio.fullname" . }}-pvc
  labels:
{{ include "grommunio.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.grommunio.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.grommunio.persistence.size }}
  {{- if .Values.grommunio.persistence.storageClass }}
  storageClassName: {{ .Values.grommunio.persistence.storageClass }}
  {{- end }}
{{- end }}
