# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.grommunio.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "grommunio.fullname" . }}-pvc
  labels:
{{ include "grommunio.labels" . | nindent 4 }}
    backup-tier: "b"
    k8up/backup: "true"
spec:
  accessModes:
    - {{ .Values.grommunio.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.grommunio.persistence.size }}
  {{- if .Values.grommunio.persistence.storageClass }}
  storageClassName: {{ .Values.grommunio.persistence.storageClass }}
  {{- end }}
{{- end }}
