# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grommunio.fullname" . }}-secret
  labels:
{{ include "grommunio.labels" . | nindent 4 }}
type: Opaque
stringData:
  GROMMUNIO_DB_PASSWORD: {{ .Values.grommunio.db.password | default (randAlphaNum 32) | quote }}
  GROMMUNIO_CACHE_PASSWORD: {{ .Values.grommunio.cache.password | default (randAlphaNum 32) | quote }}
  GROMMUNIO_OIDC_CLIENT_SECRET: {{ .Values.grommunio.auth.oidc.clientSecret | default (randAlphaNum 32) | quote }}
  {{- if .Values.grommunio.auth.saml.identityProviderCert }}
  GROMMUNIO_SAML_IDP_CERT: {{ .Values.grommunio.auth.saml.identityProviderCert | quote }}
  {{- end }}
  GROMMUNIO_LDAP_BIND_PASSWORD: {{ .Values.grommunio.ldap.bindPassword | default (randAlphaNum 32) | quote }}
